In [ ]:
!pip install -q bertopic umap-learn hdbscan

In [ ]:
import re
import pandas as pd
import nltk
from nltk.tokenize import sent_tokenize
from sentence_transformers import SentenceTransformer
import torch
nltk.download("punkt")
nltk.download("punkt_tab")
import numpy as np
from bertopic import BERTopic
from bertopic.vectorizers import ClassTfidfTransformer
from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import (CountVectorizer, ENGLISH_STOP_WORDS)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [ ]:
from google.colab import drive
from pathlib import Path
drive.mount("/content/drive")
OUT_DIR = Path("/content/drive/MyDrive/thesis_results/BERTopic")
OUT_DIR.mkdir(parents=True, exist_ok=True)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

**Splitting the dataset into sentences**

In [ ]:
SCOTBESS = pd.read_csv("SCOTBESS.csv")

print(SCOTBESS.columns.tolist())
print("Documents:", len(SCOTBESS))

['document_id', 'project', 'filename', 'source', 'final_masked_text']
Documents: 1675

In [ ]:
#splitting the text into sentences as reccomended in the BERTopic documentation
#retaining IDs for tracing to which document the sentence belongs to
sentence_rows = []

for row in SCOTBESS.itertuples(index=False):
    for sentence_id, sentence in enumerate(sent_tokenize(row.final_masked_text)):
        sentence = re.sub(r"\s+", " ", sentence).strip()

        sentence_rows.append({
            "document_id": row.document_id,
            "sentence_id": sentence_id,
            "sentence_text": sentence,
            "project": row.project,
            "filename": row.filename,
            "source": row.source})

sentences_df = pd.DataFrame(sentence_rows)
sentences = sentences_df["sentence_text"].tolist()

print("Documents:", len(SCOTBESS))
print("Extracted sentences:", len(sentences_df))

sentences_df.head()

Documents: 1675
Extracted sentences: 33527

,document_id,sentence_id,sentence_text,project,filename,source
0,0,0,The ground on which the proposed energy site i...,Aberdeen_City_210665_DPP,210665_DPP-Objects-Mr_Marc_Evans_FULL_-2025345...,comment_structure
1,0,1,The embankment would structurally safe.,Aberdeen_City_210665_DPP,210665_DPP-Objects-Mr_Marc_Evans_FULL_-2025345...,comment_structure
2,0,2,A part of the site is not owned by the propose...,Aberdeen_City_210665_DPP,210665_DPP-Objects-Mr_Marc_Evans_FULL_-2025345...,comment_structure
3,1,0,We have serious reservations that there has no...,Aberdeen_City_210665_DPP,extracted_210665_DPP-Objects_-_Ken_Cumming__Ve...,no_structure
4,1,1,From the information supplied the site will ha...,Aberdeen_City_210665_DPP,extracted_210665_DPP-Objects_-_Ken_Cumming__Ve...,no_structure

In [ ]:
sentences_df["word_count"] = (sentences_df["sentence_text"].str.split().str.len())

sentences_df["word_count"].describe()

count    33527.000000
mean        22.390461
std         13.627202
min          1.000000
25%         14.000000
50%         21.000000
75%         28.000000
max        418.000000
Name: word_count, dtype: float64

In [ ]:
#checking very long sentences
with pd.option_context("display.max_colwidth", None,"display.max_rows", 10):
    display(sentences_df.nlargest(10, "word_count")[["document_id","sentence_id","word_count", "sentence_text"]])
    #the long senteces are valid, their lenght results from people not using punctuation

,document_id,sentence_id,word_count,sentence_text
13103,1909,1,418,"There was a visit on Friday 28th of October from [PERSON], the attitude of said person was that regardless of how the residents feel about the impact on the environment, the disruption it will cause to our lives, the fact that we have lived for the past 5 years putting up with the work being done to the already well established power plant on [PLACE] that we were assured would stop by 2020 then covid struck, they then said they needed another year with the work on site to be completed then it would be totally unmanned, this has never happened they are still there working with machinery, and I am assuming that it is the infrastructure for the battery plants, the noise is constant from the sub station there is a buzzing that comes from the overhead pylons that becomes like a toothache you can’t get rid of.I keep horses on the land that borders onto the land that is earmarked for development, I exercise the horses daily on [PLACE] which at times can be quite challenging with the amount of traffic that is on the road just now, if this development goes ahead I feel I will become a prisoner in my own home as I will not be able to negotiate the volume of traffic that the development will cause,my horses being flight animals will also be held captive, they would also need to close the road to get the containers (the size of double decker buses) on site and there is going to be 18 of them with fans on each container running 24-7 to keep them cool which is going to create more noise and the fact they want to put a sonic fence around it to try and lessen the noise impact quite frankly scares the life from me.and all being done without consultation with the residents in the surrounding area .When I purchased my property it was the fact it was on a green belt and would be good for my mental health and the well-being of my animals, was it not the Scottish government that have been telling us all to get healthier and do more exercise get out into the fresh air experience the pleasure’s the countryside has to offer, we will be living with-in an industrial site on our doorstep with constant noise and daily disruptions, I would like there to be more negotiation and reassurance’s before this is( in the words of the planning officer rubber stamped)."
32269,3841,4,361,"So this is going to just be another hurdle we need to cross when we come to it, the standard net zero cart before the horse planning In diagram reference 10109449 S4N [PLACE] Design, the diagram key showed a blue line for a SuDs lines feature, excuse my possible ignorance of understanding this drawing, but this line is showing as directly connecting to the [PLACE], which should there be any run off/contamination from this facility it will flow to this burn which travels through farmland and joins the local river When reviewing the SEPA food risk map (which I have included) the [PLACE] area already shows as being an affected area, and this is prior to this application being constructed or that of West of Orkney’s massive substation which would also be in close proximity to this facility (which has planning in principal already) or [PLACE] BESS up to 300MW (ECU ref - [APPLICATION_CODE]) neither of which I add appear on any drawings/diagrams or visualisations for this application All to which I would imagine cumulatively would make this issue of flood risk increase There’s currently 1 4 GW of BESS in the planning process on the stretch of road between [PLACE]/[PLACE]/[PLACE] (a distance of 2 5 miles at most) impact and risk of these and the other developments is unacceptable As a close neighbour of this site and the many other applications for transmission which are being applied for in this area, I fully believe the individuals who make the decision on this application should have a site visit of the area being made aware of all current applications prior to deciding, to visualise how this area for which the [PLACE] runs through is being industrialised, affecting not only the nearby residents/businesses, but also wildlife and nature When put together the damage that this and other applications for this area alone are causing through digging up of natural land of which some include peatland, replacing it with concrete and hardcore, felling of woodland, the hundreds of thousands of litres of fuel being burned through the plant, HGVs and construction traffic, how long will it actually take to negate the damage caused?"
6743,1347,4,323,"Two sites have been offered to the developers, from local farmers, which are much closer and much more suitable for this development but which have been ignored because they are already financially committed to this site This land is rural, residential and farming land and therefore the scale and industrial character of the development is incompatible with the area While renewable energy storage is important, it must be sited and designed with public safety, environmental protection, and local amenity in mind - this development does not do that Visual and Financial Impacts: The site will be visible from our house and from the roadside ([PLACE]) - it will also be even more visible for the properties that sit on the hill behind - no viewpoint from our property has been uploaded to the planning portal The red marked areas on the map do not include our house which is right next to the site and we have not had official letters from the council to advise of the planning application which we find ridiculous - people have had letters that cannot even see the site from their properties The area is a rural, low residential impact area which is not suitable for this kind of development The house values for all of the properties around the development will be affected by a considerable amount - when the developers were questioned about this factor, they agreed that the drop in values could be as much as a third of the current values - this is not an inconsiderable amount of money for all concerned Safety & Fire Risk Lithium-ion Battery storage sites have been known to catch fire and be an explosion risk particularly in the event of thermal runaway - fumes and contamination are a risk to humans and wildlife On this basis I OBJECT to the above noted development and ask that you REJECT this application on its suitability in this location"
6742,1347,3,280,"Peacefulness was one of the reasons we chose to live here There is a risk for soil and water contamination if the battery fluids leak or catch fire, the emission of toxic gases during thermal runaway would impact the air quality and have an adverse effect on health for those in close proximity Runoff from the development looks as though it will be directed to the burn on the [PLACE] - this would entail having to pump any overflow as the burn is uphill from the site - therefore more machinery will be in place causing more noise pollution In initial plans shown to us by the developers, there was no mention of physical buildings, it was containers surrounded by a bund, however the plans now state that some of the buildings will be of brick and therefore presumably underpinned with foundations which will further disturb the locale If planning was sought in any other case for a container storage unit in the middle of an agricultural field in a rural location, it would very probably be refused Location Suitability: The developers have not carried out due diligence in the initial stages of the planning process and should have considered all facts relating to the site and the opinions of the surrounding residents, before starting the planning process They have gone ahead with the process on the basis that they were offered the land by the landowners and the landowners gave a false impression that everyone in the local area was for the development This site is 5km from the substation at [PLACE] which means that the connections to the grid will themselves have a negative impact on the area."
17044,2341,0,236,I object to this development which will add 500MW of battery storage to the 300MW already approved and in progress at the same location Several other proposed developments now seeking screening opinion—notably that at [PLACE] for 300MW would if approved take total battery capacity at the [PLACE] to well over 1000MW For comparison the largest development in Europe is 98MW the largest in the world is 400MW Such a concentration of energy supply at a single site raises serious strategic risk in the event of fire or terrorist incident neither of which is given detailed consideration in the project documents I support the Scottish Governments policy on renewable energy but I object to the scale of this proposal and its disruptive impact on local residents from construction traffic noise and light pollution throughout the life of the project and the irrevocable loss of amenity from this major change to the character of an unspoiled landscape on Kilmarnocks doorstep The Scottish Governments screening opinion was set out in its letter of 12 July 2022 but paid no attention to the other major developments now approved or proposed for the site The East [PLACE] Planning Committee meeting of 25 November 2022 noted the comment of the Chief Governance Officer that the cumulative impact of the several other screening proposals now put forward would require attention This should now be considered before the current proposal is allowed to proceed
18909,2537,1,233,"The proposed site will be visible from the main bypass which will ruin the beautiful, green countryside which borders the southbound carriageway of the [PLACE] between [PLACE] and [PLACE]; The proposed site is bordered by residential properties and a busy caravan park, all of which will be negatively impacted financially and personally by this development; The proposed site will be 2 years in construction and will be accessed via the [PLACE] which is an already congested road providing blue-light access to Ayr University Hospital; The developers plan to build a new access road just off the [PLACE], prior to the existing entrance to [PLACE], which will cause additional pressures on an already busy road/roundabout infrastructure; The groundworks for this proposal will require heavy plant machinery travelling to and from the site at all times of day and night; An existing underground gas pipe and overhead electrical cables are already in existence on the proposed development site; Lithium batteries are a fire risk which cannot be extinguished once on fire – any resultant flames/smoke would bring the [PLACE] to a standstill and cause significant health and safety implications to nearby residents and farm livestock; The power station and storage facility will emit noise to the detriment and annoyance of neighbouring properties; The site will not be manned with security monitored remotely and be subject to motion-censor lighting leaving it vulnerable to theft and arson."
20562,2642,0,196,"Adverse impact on landscape – tranquil and beautiful glen will be industrialised beyond recognition Protected wildlife – No EIA and no surveys completed in advance of application when previous surveys for other infrastructure projects have identified legally protected species (mammals and birds) in this area Trees – Tree removal and unclear and unconvincing detail of how ancient woodland will be protected and replanting managed Access / traffic – 2 years of construction traffic affecting locals and [PLACE] and west coast route drivers Fire Safety – full fire safety plan not been produced in advance of application to deal with lack of mains water, distance from fire stations, single main access, containment of contaminated water and toxic fumes in event of incident Need – already have 3 up to 50MW battery storage facilities approved nearby so NO NEED for another massive 200MW BESS in this area Cumulative impact – already have 2 wind farms (inc. one extension), an upgraded pylon line, a substation, plus a 50MW BESS, another wind farm and another extension, both including BESS, approved but not yet built – there is enough energy infrastructure here already and these plans conflict with those already approved."
32947,3957,0,195,"Landscape & Visual Impact 16.3ha site (size of 23 football fields) with a 25m slope requiring six terraces 470 containers, 4,608 solar panels, three 12m transformers Highly visible despite 4m fencing and 8m bunds Noise Pollution Incomplete noise report, no cumulative impact considered Experts warn noise could triple existing levels Terrain makes noise mitigation difficult Fire Risk & Safety Lithium-ion battery fires cannot be fully extinguished No consultation with Scottish Fire & Rescue No evacuation plan for residents or livestock [ORGANIZATION] safety guidelines not followed Water & Drainage Fire suppression needs massive water volumes—no source confirmed Risks to drainage, groundwater, private water supplies, and rivers ([PLACE], [PLACE]) No proper modelling of impermeable layers and terracing impact Traffic & Infrastructure Severe disruption to single-track roads Construction Management Plan underestimates vehicle movements Biodiversity No EIA for badgers, bats, ground-nesting birds, or Ancient Woodland Fire runoff could cause major contamination Decommissioning No plan for removing impermeable membranes, concrete, or bunds after 25 years Lack of Community Benefit No guaranteed local jobs or investment £2.5m/year community benefit recommended by Scottish Government ignored Policy Failure: Fails National Planning Framework 4 (Policy 11) – significant landscape impact and zero community benefit."
12613,1854,2,174,"My other concerns are .The Plant will be situated within an industrial site and will create no permanent Jobs and generally electrical power generation and storage historically was situated on the peripheral of populated arears due to safety This site is close to a nearby river and would be considered to be part of the floodplain.Also the real risk of battery thermal run away which could cause a major incident and the fact that the company building this plant could not demonstrate a clear procedure or record of safety was very concerning .I would strongly advise the board considering this application liase with fire service to ascertain procedure for such instances of electrical thermal run away fires and look at safety record of other such facilities I am very much in favor of cutting greenhouse gasses and creating a greener clean Electrical generation Grid,but Safety and safety procedures and the demonstration that such plants are safe must be at the heart of all such applications prior to them being placed nearby to local residents."
11494,1821,37,170,"Some comments are provided below: a. VP 1 – [PLACE] – this viewpoint, 400m to the south of the application site, significantly underplays the likely visual effect from the 3m high containers, the 4m high fencing and the new landscaping all of which would be a new and alien feature in the view b. VP 2 – to the north of the site – it is not at all clear that the application proposals have been properly scaled in this montage from a location that is just 100m from the site boundary c. VP 3 – [PLACE], 500m to the north of the site – it is unclear what this landscape and visual effects this is meant to show as the written assessment advises that there would be no visibility of the proposal from this location d. VP 4 – [PLACE] to [PLACE], 800m north west of the site – again it is unclear what effects this viewpoint is meant to be illustrating as there would be no visibility 10."

In [ ]:
documents = sentences_df["sentence_text"].tolist()

print("Sentences used:", len(documents))

Sentences used: 33527

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

embedding_model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2", device=device)

embeddings = embedding_model.encode(documents, batch_size=32, show_progress_bar=True, normalize_embeddings=True)

print("Embeddings shape:", embeddings.shape)
np.save(OUT_DIR / "SCOTBESS_MPNET_SENTENCE_EMBEDDINGS.npy", embeddings)

Device: cuda

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/1048 [00:00<?, ?it/s]

Embeddings shape: (33527, 768)

**Topic exploration with BERTopic**

In [ ]:
sentences_df = pd.read_csv("SCOTBESS_SENTENCES.csv")
embeddings = np.load("SCOTBESS_MPNET_SENTENCE_EMBEDDINGS.npy")

documents = sentences_df["sentence_text"].tolist()

assert len(documents) == embeddings.shape[0]
print(embeddings.shape)

(33527, 768)

In [ ]:
umap_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric="cosine", random_state=42)
hdbscan_model = HDBSCAN(min_cluster_size=50, min_samples=10, metric="euclidean", cluster_selection_method="eom", prediction_data=True)

placeholder_terms = {"person","place","email","phone","link","application_code","organization"}

custom_stopwords = list(set(ENGLISH_STOP_WORDS).union(placeholder_terms))

vectorizer_model = CountVectorizer(stop_words=custom_stopwords, ngram_range=(1, 2), min_df=5)

ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

In [ ]:
topic_model = BERTopic(
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer_model,
    ctfidf_model=ctfidf_model,
    nr_topics=30, # tested several values; reducing to 30 topics produced the most interpretable results, although some noisy topics remain.
    top_n_words=10,
    calculate_probabilities=False,
    verbose=True)

topics, probabilities = topic_model.fit_transform(documents, embeddings)

2026-08-02 17:34:23,070 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-08-02 17:35:22,623 - BERTopic - Dimensionality - Completed ✓
2026-08-02 17:35:22,625 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-08-02 17:35:28,824 - BERTopic - Cluster - Completed ✓
2026-08-02 17:35:28,825 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2026-08-02 17:35:29,820 - BERTopic - Representation - Completed ✓
2026-08-02 17:35:29,822 - BERTopic - Topic reduction - Reducing number of topics
2026-08-02 17:35:29,880 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-08-02 17:35:30,876 - BERTopic - Representation - Completed ✓
2026-08-02 17:35:30,882 - BERTopic - Topic reduction - Reduced number of topics from 124 to 30

In [ ]:
topic_info = topic_model.get_topic_info()

display(topic_info.head(30))

outlier_count = sum(topic == -1 for topic in topics)

print(f"Topics found: {(topic_info['Topic'] != -1).sum()}")
print(f"Outliers: {outlier_count:,} ({outlier_count / len(topics):.1%})")

,Topic,Count,Name,Representation,Representative_Docs
0,-1,13864,-1_energy_infrastructure_development_public,"[energy, infrastructure, development, public, ...",[I wish to object to planning application [APP...
1,0,3412,0_npf4_eia_policies_national planning,"[npf4, eia, policies, national planning, frame...",[NPF4 Policies 22 and 23 require developments ...
2,1,2125,1_road_traffic_vehicles_roads,"[road, traffic, vehicles, roads, access, const...","[Additionally, the anticipated closure of [PLA..."
3,2,1859,2_battery_storage_batteries_energy storage,"[battery, storage, batteries, energy storage, ...",[Public Health and Safety Threats The [PLACE] ...
4,3,1551,3_noise_background_light pollution_levels,"[noise, background, light pollution, levels, p...","[Additionally, HWLDP Policy 28 stipulates that..."
5,4,1291,4_species_habitat_birds_wildlife,"[species, habitat, birds, wildlife, trees, bat...","[Construction activities, noise pollution, and..."
6,5,1265,5_bess_proposed bess_bess site_bess sites,"[bess, proposed bess, bess site, bess sites, b...",[The [ORGANIZATION] strongly advises against s...
7,6,1246,6_emergency_explosion_safety plan_environmenta...,"[emergency, explosion, safety plan, environmen...",[Given the absence of a comprehensive fire saf...
8,7,1006,7_substation_turbines_metres_lines,"[substation, turbines, metres, lines, substati...",[The construction of multiple 400kV overhead p...
9,8,971,8_landscape visual_cultural_heritage_historical,"[landscape visual, cultural, heritage, histori...",[Cultural Heritage - The [PLACE] The developme...
10,9,915,9_water_flooding_flood_runoff,"[water, flooding, flood, runoff, flood risk, p...","[Furthermore, SEPA flood risk mapping indicate..."
11,10,719,10_consultation_consultation process_engagemen...,"[consultation, consultation process, engagemen...",[Deficiencies in the Consultation Process The ...
12,11,662,11_carefully_castle_maintained_11,"[carefully, castle, maintained, 11, years, int...",[The visual and symbolic significance of the C...
13,12,471,12_employment_offers_benefit_community benefits,"[employment, offers, benefit, community benefi...",[This large-scale project offers no clear comm...
14,13,465,13_object_strongly_reject_rejected,"[object, strongly, reject, rejected, urge, ref...","[Given the risks to public safety, the environ..."
15,14,307,14_prompting_transparency_unanswered_gone,"[prompting, transparency, unanswered, gone, de...",[Despite attempts to seek clarification throug...
16,15,244,15_consent_imposed_driven_positive,"[consent, imposed, driven, positive, active, d...","[A project that impacts daily life, health, he..."
17,16,238,16_carbon monoxide_monoxide_volatile_dioxide,"[carbon monoxide, monoxide, volatile, dioxide,...",[Given the prevailing wind patterns in the [PL...
18,17,164,17_corrosive_thermal runaway_runaway_thermal,"[corrosive, thermal runaway, runaway, thermal,...",[Instances of thermal runaway can lead to unma...
19,18,111,18_collective_evaluate_extent_isolation,"[collective, evaluate, extent, isolation, full...",[It is imperative to evaluate the collective e...
20,19,100,19_containers_shipping_shipping containers_dim...,"[containers, shipping, shipping containers, di...",[There will be 470 20-foot shipping containers...
21,20,74,20_environmental information_public access_mea...,"[environmental information, public access, mea...",[The UK's commitment to the Aarhus Convention ...
22,21,73,21_barriers_vistas_unobstructed_allure,"[barriers, vistas, unobstructed, allure, ident...",[While acoustic barriers may offer some noise ...
23,22,65,22_security fencing_highvoltage_barriers_fencing,"[security fencing, highvoltage, barriers, fenc...",[The installation of necessary security fencin...
24,23,60,23_disingenuous_information given_investigated...,"[disingenuous, information given, investigated...","[They have been disingenuous regarding this., ..."
25,24,58,24_test_key policy_corresponding_perceived,"[test, key policy, corresponding, perceived, p...","[In conclusion, the proposal fails in respect ..."
26,25,56,25_80_78_77_71,"[80, 78, 77, 71, 72, 90, , , , ]","[80., 80., 80.]"
27,26,55,26_stop_acceptable_happen_unacceptable,"[stop, acceptable, happen, unacceptable, reall...",[I really do not think this is the right way f...
28,27,50,27_appendix_documentation submitted_supporting...,"[appendix, documentation submitted, supporting...","[However, supporting documentation was submitt..."
29,28,50,28_specifically_iii_ii_iv,"[specifically, iii, ii, iv, 1a, 19, repeated, ...","[Specifically: a., Specifically: a., Specifica..."

Topics found: 29
Outliers: 13,864 (41.4%)

In [ ]:
sentences_df["topic"] = topics
sentences_df["topic_probability"] = probabilities

In [ ]:
topic_info = topic_model.get_topic_info()

topic_name_map = dict(zip(topic_info["Topic"], topic_info["Name"]))

sentences_df["topic"] = topics
sentences_df["topic_probability"] = probabilities
sentences_df["topic_name"] = (sentences_df["topic"].map(topic_name_map))
sentences_df.head()

,document_id,sentence_id,sentence_text,project,filename,source,topic,topic_probability,topic_name
0,0,0,The ground on which the proposed energy site i...,Aberdeen_City_210665_DPP,210665_DPP-Objects-Mr_Marc_Evans_FULL_-2025345...,comment_structure,1,1.000000,1_road_traffic_vehicles_roads
1,0,1,The embankment would structurally safe.,Aberdeen_City_210665_DPP,210665_DPP-Objects-Mr_Marc_Evans_FULL_-2025345...,comment_structure,8,0.707920,8_landscape visual_cultural_heritage_historical
2,0,2,A part of the site is not owned by the propose...,Aberdeen_City_210665_DPP,210665_DPP-Objects-Mr_Marc_Evans_FULL_-2025345...,comment_structure,0,1.000000,0_npf4_eia_policies_national planning
3,1,0,We have serious reservations that there has no...,Aberdeen_City_210665_DPP,extracted_210665_DPP-Objects_-_Ken_Cumming__Ve...,no_structure,2,0.611774,2_battery_storage_batteries_energy storage
4,1,1,From the information supplied the site will ha...,Aberdeen_City_210665_DPP,extracted_210665_DPP-Objects_-_Ken_Cumming__Ve...,no_structure,-1,0.000000,-1_energy_infrastructure_development_public

In [ ]:
display(topic_info.head(30))

outlier_count = (sentences_df["topic"] == -1).sum()

print("Topics:", (topic_info["Topic"] != -1).sum())
print(f"Outliers: {outlier_count:,}, {outlier_count / len(sentences_df):.1%})")

,Topic,Count,Name,Representation,Representative_Docs
0,-1,13864,-1_energy_infrastructure_development_public,"[energy, infrastructure, development, public, ...",[I wish to object to planning application [APP...
1,0,3412,0_npf4_eia_policies_national planning,"[npf4, eia, policies, national planning, frame...",[NPF4 Policies 22 and 23 require developments ...
2,1,2125,1_road_traffic_vehicles_roads,"[road, traffic, vehicles, roads, access, const...","[Additionally, the anticipated closure of [PLA..."
3,2,1859,2_battery_storage_batteries_energy storage,"[battery, storage, batteries, energy storage, ...",[Public Health and Safety Threats The [PLACE] ...
4,3,1551,3_noise_background_light pollution_levels,"[noise, background, light pollution, levels, p...","[Additionally, HWLDP Policy 28 stipulates that..."
5,4,1291,4_species_habitat_birds_wildlife,"[species, habitat, birds, wildlife, trees, bat...","[Construction activities, noise pollution, and..."
6,5,1265,5_bess_proposed bess_bess site_bess sites,"[bess, proposed bess, bess site, bess sites, b...",[The [ORGANIZATION] strongly advises against s...
7,6,1246,6_emergency_explosion_safety plan_environmenta...,"[emergency, explosion, safety plan, environmen...",[Given the absence of a comprehensive fire saf...
8,7,1006,7_substation_turbines_metres_lines,"[substation, turbines, metres, lines, substati...",[The construction of multiple 400kV overhead p...
9,8,971,8_landscape visual_cultural_heritage_historical,"[landscape visual, cultural, heritage, histori...",[Cultural Heritage - The [PLACE] The developme...
10,9,915,9_water_flooding_flood_runoff,"[water, flooding, flood, runoff, flood risk, p...","[Furthermore, SEPA flood risk mapping indicate..."
11,10,719,10_consultation_consultation process_engagemen...,"[consultation, consultation process, engagemen...",[Deficiencies in the Consultation Process The ...
12,11,662,11_carefully_castle_maintained_11,"[carefully, castle, maintained, 11, years, int...",[The visual and symbolic significance of the C...
13,12,471,12_employment_offers_benefit_community benefits,"[employment, offers, benefit, community benefi...",[This large-scale project offers no clear comm...
14,13,465,13_object_strongly_reject_rejected,"[object, strongly, reject, rejected, urge, ref...","[Given the risks to public safety, the environ..."
15,14,307,14_prompting_transparency_unanswered_gone,"[prompting, transparency, unanswered, gone, de...",[Despite attempts to seek clarification throug...
16,15,244,15_consent_imposed_driven_positive,"[consent, imposed, driven, positive, active, d...","[A project that impacts daily life, health, he..."
17,16,238,16_carbon monoxide_monoxide_volatile_dioxide,"[carbon monoxide, monoxide, volatile, dioxide,...",[Given the prevailing wind patterns in the [PL...
18,17,164,17_corrosive_thermal runaway_runaway_thermal,"[corrosive, thermal runaway, runaway, thermal,...",[Instances of thermal runaway can lead to unma...
19,18,111,18_collective_evaluate_extent_isolation,"[collective, evaluate, extent, isolation, full...",[It is imperative to evaluate the collective e...
20,19,100,19_containers_shipping_shipping containers_dim...,"[containers, shipping, shipping containers, di...",[There will be 470 20-foot shipping containers...
21,20,74,20_environmental information_public access_mea...,"[environmental information, public access, mea...",[The UK's commitment to the Aarhus Convention ...
22,21,73,21_barriers_vistas_unobstructed_allure,"[barriers, vistas, unobstructed, allure, ident...",[While acoustic barriers may offer some noise ...
23,22,65,22_security fencing_highvoltage_barriers_fencing,"[security fencing, highvoltage, barriers, fenc...",[The installation of necessary security fencin...
24,23,60,23_disingenuous_information given_investigated...,"[disingenuous, information given, investigated...","[They have been disingenuous regarding this., ..."
25,24,58,24_test_key policy_corresponding_perceived,"[test, key policy, corresponding, perceived, p...","[In conclusion, the proposal fails in respect ..."
26,25,56,25_80_78_77_71,"[80, 78, 77, 71, 72, 90, , , , ]","[80., 80., 80.]"
27,26,55,26_stop_acceptable_happen_unacceptable,"[stop, acceptable, happen, unacceptable, reall...",[I really do not think this is the right way f...
28,27,50,27_appendix_documentation submitted_supporting...,"[appendix, documentation submitted, supporting...","[However, supporting documentation was submitt..."
29,28,50,28_specifically_iii_ii_iv,"[specifically, iii, ii, iv, 1a, 19, repeated, ...","[Specifically: a., Specifically: a., Specifica..."

Topics: 29
Outliers: 13,864, 41.4%)

In [ ]:
topic_coverage = (sentences_df[sentences_df["topic"] != -1].groupby("topic")
    .agg(
        sentences=("sentence_text", "size"),
        documents=("document_id", "nunique"),
        projects=("project", "nunique"),
        mean_probability=("topic_probability", "mean")).reset_index())

topic_coverage["topic_name"] = (topic_coverage["topic"].map(topic_name_map))
topic_coverage = topic_coverage.sort_values("sentences", ascending=False)

display(topic_coverage.head(30))

,topic,sentences,documents,projects,mean_probability,topic_name
0,0,3412,969,75,0.800487,0_npf4_eia_policies_national planning
1,1,2125,669,74,0.955910,1_road_traffic_vehicles_roads
2,2,1859,837,76,0.919506,2_battery_storage_batteries_energy storage
3,3,1551,488,63,0.934767,3_noise_background_light pollution_levels
4,4,1291,461,61,0.783943,4_species_habitat_birds_wildlife
5,5,1265,480,62,0.878801,5_bess_proposed bess_bess site_bess sites
6,6,1246,593,70,0.814461,6_emergency_explosion_safety plan_environmenta...
7,7,1006,446,64,0.937985,7_substation_turbines_metres_lines
8,8,971,471,68,0.927151,8_landscape visual_cultural_heritage_historical
9,9,915,367,55,0.816592,9_water_flooding_flood_runoff
10,10,719,293,49,0.842776,10_consultation_consultation process_engagemen...
11,11,662,181,43,0.872184,11_carefully_castle_maintained_11
12,12,471,265,53,0.832879,12_employment_offers_benefit_community benefits
13,13,465,364,59,0.905582,13_object_strongly_reject_rejected
14,14,307,212,58,0.736179,14_prompting_transparency_unanswered_gone
15,15,244,186,50,0.856737,15_consent_imposed_driven_positive
16,16,238,122,32,0.859345,16_carbon monoxide_monoxide_volatile_dioxide
17,17,164,118,29,0.869594,17_corrosive_thermal runaway_runaway_thermal
18,18,111,91,30,0.956373,18_collective_evaluate_extent_isolation
19,19,100,54,26,0.751695,19_containers_shipping_shipping containers_dim...
20,20,74,39,15,1.000000,20_environmental information_public access_mea...
21,21,73,72,6,0.985532,21_barriers_vistas_unobstructed_allure
22,22,65,65,8,0.945988,22_security fencing_highvoltage_barriers_fencing
23,23,60,51,27,0.995774,23_disingenuous_information given_investigated...
24,24,58,37,22,0.999996,24_test_key policy_corresponding_perceived
25,25,56,3,3,1.000000,25_80_78_77_71
26,26,55,51,24,0.990028,26_stop_acceptable_happen_unacceptable
27,27,50,31,25,1.000000,27_appendix_documentation submitted_supporting...
28,28,50,29,23,1.000000,28_specifically_iii_ii_iv

In [ ]:
for topic_id in topic_info.loc[topic_info["Topic"] != -1, "Topic"].head(30):
    print("\n" + "=" * 80)
    print("TOPIC:", topic_id, topic_name_map[topic_id])

    examples = ( sentences_df[sentences_df["topic"] == topic_id].sort_values("topic_probability", ascending=False).head(10))

    for sentence in examples["sentence_text"]:
        print("-", sentence)

================================================================================
TOPIC: 0 0_npf4_eia_policies_national planning
- This installation along with any other similar proposals needs to be sited well away from dwelling houses.
- Allowing this proposal to go ahead would fundamentally contradict the risk assessments, safety protocols, and development exclusion zones that have been enforced for years to protect critical infrastructure, the environment, and public health.
- A part of the site is not owned by the proposed development and is owned by another party - I am lead to believe the current owner is trying to adopt our ground into the proposed site.
- Policy Breaches 5.
- As such Policy B6 would apply.
- Without this information, it is not possible to determine whether the modelling presented is accurate or reflective of the development’s year-round impact.
- No information has been provided about how local wildlife will be protected or relocated, or whether the project includes any biodiversity assessment or mitigation strategy.
- Many Thanks [PERSON]
- My name is [PERSON].
- Rehabilitation: Where are the guarantees that the land will be restored at the end of the 25-years of the project – for example, how is the impermeable membrane and the concrete going to be removed from the ground?

================================================================================
TOPIC: 1 1_road_traffic_vehicles_roads
- Mitigation measures such as designated haul routes, vehicle weight restrictions, and scheduled maintenance.
- The ground on which the proposed energy site is to be situated is not fit for purpose to hold any weight of machinery as the walls of the current embankment are currently subsiding due to weight of vehicles sitting on it at present.
- Given that there is a major obstacle (the [PLACE]) between the two sites clarification needs to be provided as to how this piece of infrastructure can be achieved.
- Traffic impact assessments 3.
- Both during construction and operation the heavy vehicle traffic will increase dramatically at a busy juncture in the road.
- This area is already noted as high risk and this would only increase the likelihood of accident and death.
- Increased risk of road traffic collisions for vehicles entering and leaving the proposed development (50 mph road).
- A full road condition survey before and after construction 2.
- There is also the potential for an increase in road traffic accidents.
- This is likely to increase the possibility of a major incident and therefore similar objections would apply.

================================================================================
TOPIC: 2 2_battery_storage_batteries_energy storage
- Given the nature of the proposed Battery Energy Storage System (BESS) site and potential risks involved, it is vital that a clear, accessible summary or draft of the ERP be made available for public review prior to granting permission.
- I strongly object to these disasterous sites, battery storage s catch fire, where does the toxic fumes off a burning battery go?
- I am writing to register my formal objection to the application [APPLICATION_CODE] for a 500MW battery energy storage system (BESS) and associated infrastructure at [PLACE], [PLACE], [PLACE].
- Lithium battery are lethal as they give off Toxic Gas’s, which could reach the village with in minutes depending on how the wind blows, these gasses can be FATAL, can can burn the skin if it touches you.
- This letter constitutes my objection to the proposed 500MW battery energy storage system (BESS) at [PLACE], [PLACE], [PLACE], ref: [APPLICATION_CODE].
- The risks associated with battery fire in BES facilities are significant and not yet fully understood.
- The recent (Q1/2025) battery unit fire at [PLACE] BESS demonstrates that BES units are prone to fire which is difficult to manage.
- Rational like we can recycle it is in reality nonsenve as UK barely recycle 1% lithium Which leads to my next objection use of lithium ion batteries WHY their are much safer batteries abaliable to use.
- There is also a problem relating to the safety of these battery storage installations with inappropriate fire safety measures available and no UK legislation for the [ORGANIZATION] to legislate against.
- Battery energy storage systems (BESS).

================================================================================
TOPIC: 3 3_noise_background_light pollution_levels
- Loss of Amenity: Increased noise, traffic, or other disruptions to residents' quality of life.
- Our client notes that no assessment appears to have been carried out to establish the potential noise impact which the development will have on our client's premises, despite it being the closest premises.
- The contrast between this and the mechanical hum, fan noise, and construction activity that would come with a 500MW BESS is stark and distressing to imagine.
- Certain age brackets are able to hear a variety of sound frequencies from such facilities.
- Noise level: We understand that the developer intends to erect a noise suppression (acoustic) fence as there will be a level of background noise from the air conditioning system within the BESS containers.
- However, sound is omnidirectional so unless the whole storage facility was enclosed the noise level will not be adequately reduced.
- The tonal buzzing and humming resulting from the high voltage electrical equipment onsite will be offensive to people living nearby.
- The noise is another issue which is being played down and the acoustic fence being suggested to partially surround this installation may actually increase noise levels.
- The noise is another issue which is being played down and the acoustic fence being suggested to partially surround this installation may actually increase noise levels.
- Objections based on noise concerns for nearby residents in the area, especially in the evening.

================================================================================
TOPIC: 4 4_species_habitat_birds_wildlife
- 7) [PLACE] and surrounding area is home to bats, owls, swallows and swifts, animals which rely on outbuildings such as those on the [PLACE] site for nesting sites.
- The nature and extent of this site are not in keeping with the surrounding environment.
- A cumulative impact assessment on the NHZ population should be carried out.
- Outline Biodiversity Enhancement Plan NPF4 was adopted on 13 February 2023, forms part of the development plan against which this application should be determined, along with other material considerations.
- Policy 3 of NPF4 sets out a requirement for developments to deliver biodiversity enhancement.
- Policy 3 states that, ‘Development proposals for national or major development or for development that requires an Environmental Impact Assessment will only be supported where it can be demonstrated that the proposal will conserve and enhance biodiversity, including nature networks so they are in a demonstrably better state than without intervention’.
- Part b)iv of the policy states that this enhancement ‘should include nature networks, linking to and strengthening habitat connectivity within and beyond the development, secured within a reasonable timescale and with reasonable certainty.
- Pink-footed Geese regularly used Phillip Mains Mire as a communal roost (Appendix 8.1).
- They were frequently recorded flying through the turbine array on both the GVP (Figures 8.6.1 a and b), and in the direction of [PLACE] from Phillips Main onire in Focal VP surveys (Figure 8.1.7b) Although the Pink-footed Goose had both the highest number of individuals at risk height (2580, Appendix 8.2 Table 3) and the highest predicted annual collision mortality of 0.9 birds, it was scoped out of further assessment.
- We recommend that a cumulative impact assessment on NHZ2 for Pink-footed Goose should be conducted.

================================================================================
TOPIC: 5 5_bess_proposed bess_bess site_bess sites
- My constituents will be submitting objections to the [PLACE] site, and while I agree we vitally need BESS, I am equally concerned about the chosen location for this site in particular.
- I object in the strongest possible terms to the proposed/planned BESS site on [PLACE].
- The largest BESS site in Europe, does not need to be here.
- There is a lack of consideration or thought for - Wildlife and the environment thriving currently in this area Future generations from land contamination The proximity of the BESS to residential homes, [PLACE], an active travel route, the [PLACE], the train station and railway line, a shared cycle and pedestrian pathway, a popular dog walking area, and the busy [PLACE] is far too close.
- Although BESS sites have traditionally been located further from populated areas (or on land previously used for energy generation or industrial activity) and developers in other localities advocate for sites far from residential dwelling as a critical factor in the site’s choice, there is a worrying trend towards placing BESS sites in the centre of or in close proximity to human dwelling.
- Scale of Impact Inappropriate for a Rural Setting This scale of 560MW BESS highly industrial development in a rural green belt landscape covering 29Ha of grazing land is excessive.
- [PLACE], the [PLACE] and wall with its grounds and [PLACE] are category B and C listed and protected this BESS would affect the vision of these buildings from the [PLACE] and [PLACE] and for this reason alone the BESS should not be granted permission according to legislation and documentation.
- Views of or from listed buildings should not be restricted or obstructed by development The BESS should not be built on prime agricultural land as we need this land to grow food.
- No to the proposed BESS site on [PLACE]!
- - Provision of footpath through the landscape buffer to connect local paths together - Guarantee of secured funds to reinstate the ground to how it was after the 40 year lifespan of the BESS expires

================================================================================
TOPIC: 6 6_emergency_explosion_safety plan_environmental hazards
- Fires can re-start hours or even days after they have initially been extinguished.
- I would also like to request clarification on emergency preparedness during the construction phase, which carries its own set of risks and requires robust planning and communication with the local community.
- We would like to share the links below to just a couple of publications on fire issues and risks of which there are many on the internet.
- Safety Concerns 4.
- If this project is to progress, the public must be informed without delay about how emergency notifications will be issued, what immediate actions residents are expected to take in the event of a system failure, and how local impacts will be managed.
- Risk associated with failure of remotely operated control system, slowing down emergency response.
- The potential devastation a fire could cause to our client's property and the danger to their staff is of considerable concern to them.
- A full risk assessment of fire scenarios.
- Given these factors, it is imperative that a comprehensive Fire Safety and Emergency Response Plan be developed in consultation with local fire services, environmental agencies, and hazardous materials experts and shared with local residents.
- In the meantime, it is submitted that the Council needs to adopt a precautionary approach and the proposed development ought to be classed as a Major Hazard.

================================================================================
TOPIC: 7 7_substation_turbines_metres_lines
- 3) There is no detailed listing of Energy Sites around the Substation e.g 3 km radius - [APPLICATION_CODE] is highlighted.
- On a Techical Viewpoint, I would make the following comments: 1) There is no mention of MWh capacity, a key Safety/ Environmental Details.
- Our client would question whether the proposed development can be classed as a low carbon energy development as claimed by the applicant.
- The UK only emits 2% of the world’s CO2.
- Double what is needed!
- I note from a review of the Planning Statement provided by the [ORGANIZATION] that the proposed facility will connect to the grid by an underground cable to the sub-station on [PLACE].
- I am not opposed to energy progression, in fact I’ve worked in support of it for decades.
- They are creating more damage towards climate change than they are claiming to save I believe we need to look after our environment and protect its future for generations to come, but do not believe this to be the way forward, much of this infrastructure is being constructed through greed not need I ask for you to please object to this application
- Scottish Government guidance recommends £5,000 per MW per year - £2.5 million annually for this project.
- The Scottish Government “Good Practice Principles for Community Benefits from Onshore Renewable Energy Developments” document promotes community benefits of the value equivalent to £5,000 per installed megawatt per annum, index linked for the operational lifetime of the project.

================================================================================
TOPIC: 8 8_landscape visual_cultural_heritage_historical
- This area is known for its peace and tranquility.
- The noise pollution, visual disruption, and overall degradation of the rural setting have been effectively dismissed.
- Another property, [PLACE], lies approximately 100 metres away, with direct visibility into the proposed development footprint.
- Of utmost concern is the impact of the proposed BESS on the setting and experience of [PLACE], a significant and symbolic heritage asset in Scotland.
- Of utmost concern is the impact on the setting and ambiance of [PLACE], a significant and emblematic heritage site in Scotland.
- See pie chart from original CBC [PLACE] document on p13.
- 16 September 2024 This appraisal by Scottish ministers is a stark warning of the potential risks associated with this development and which are clearly incompatible with the terms and conditions of consent for [PLACE] [PLACE].
- The proposal is situated near the [PLACE] and planned developments at [PLACE] and [PLACE].
- Of utmost concern is the impact on the setting and experience of [PLACE], a significant heritage asset in Scotland.
- Landscape and Visual Impacts The proposed location is situated in a vast, open landscape with expansive views over [PLACE].

================================================================================
TOPIC: 9 9_water_flooding_flood_runoff
- Water used to extinguish such a fire would be contaminated and would most likely run downhill and into the [PLACE].
- If the static tanks are frozen during a fire event, then the stated water availability becomes meaningless.
- In the event of a thermal runaway research indicates that substantial amounts of water will be required despite the proposed fire safety management scheme on site.
- Containment of any fire would require significant amounts of water.
- There is a significant risk of contamination to private water sources in the area, including springs, burns, wells, and aquifers.
- At present, [ORGANIZATION] appears to lack a clear understanding of the locations and interconnections of private water supplies, springs, wells, and the associated inlets and outlets within the area.
- [ORGANIZATION] must therefore commission an independent and qualified body to conduct a detailed survey and analysis again at their cost, to map and clarify how all private water sources and aquifers are interlinked.
- Any runoff could introduce hazardous substances into the nearby burn, impacting the [PLACE] and [PLACE], leading to substantial environmental damage.
- Any runoff could introduce harmful chemicals into the nearby burn, ultimately affecting the [PLACE] and [PLACE], leading to significant environmental damage.
- The remote location of the site, combined with insufficient pressurised hydrants and limited emergency service accessibility, heightens these dangers, placing local residents and the environment at an unacceptable level of risk.

================================================================================
TOPIC: 10 10_consultation_consultation process_engagement_process
- I must highlight serious and deeply troubling concerns around the accuracy, impartiality, and transparency of the entire application process.
- The only notice we received was one week prior to the first consultation, which is an entirely inadequate timeframe.
- Several points require to be highlighted which the application does not address.
- The consultation processes have often been rushed, inconsistent, and poorly communicated.
- Consultation issues Despite 2 Public Consultations being held in our building we do not feel that adequate information has been made available to the local communities which will be affected.
- Inadequate Community Consultation A critical aspect of any major infrastructure project is meaningful engagement with the affected community.
- The BESS application, as it stands, falls short of these requirements.
- Lack of Community Engagement and Transparency: [ORGANIZATION] engagement with local communities has been poor during the planning process.
- Emergency response plans for such incidents remain unclear, and local fire services may not have the resources to manage large-scale battery fires effectively.
- Although there has been local consultation it has been minimal and was not clearly advertised as a second part of the same overall development.

================================================================================
TOPIC: 11 11_carefully_castle_maintained_11
- 5.
- 3.
- 2.
- 6.
- 7.
- 2.
- 3.
- 2.
- 3.
- 6.

================================================================================
TOPIC: 12 12_employment_offers_benefit_community benefits
- So called ‘Community Benefits’ are tiny.
- Day to day operations are not part of the planning considerations unless it concerns noise or light.
- - Provides no meaningful community benefit.
- There are no contingencies in the plans for this.
- Community Wealth and Benefit - The "Community Wealth Building Plan" contains no firm commitments to local employment or contractors.
- It will have a significant impact on the landscape; there is no commitment for local opportunities and no defined plan for community benefit.
- There is no benefit to the local community which breaches Scottish Government Strategy Guidelines.
- The local community will see all of the disruption but receive no benefit.
- Minimal Economic Benefit to Local Areas: Despite the large scale of this project, [ORGANIZATION] has failed to provide any evidence of significant long-term economic benefits that this project will bring to the area.
- It is of little benefit to our community, as it will not create local jobs.

================================================================================
TOPIC: 13 13_object_strongly_reject_rejected
- This alone should be grounds for immediate refusal of the application.
- [ORGANIZATION] opposes the application on the grounds that the proposed use would breach the terms of Policies B1, B6, D1 and R8 of the [PLACE] Local Development Plan 2017 as it is incompatible with existing uses in the area and raises significant safety concerns.
- If so I strongly urge you to reconsider this position.
- I object on every level of allowing this to go ahead.
- I object on every level of allowing this to go ahead.
- I also object because of the inherent dangers associated with such constructions.
- I strongly oppose this.
- Thank you to everyone who has put their comments and objections on the site.
- We therefore urge those with the power to grant planning permission to refuse this particular application.

In [ ]:
sentences_df.to_csv(OUT_DIR / "SCOTBESS_SENTENCES_WITH_TOPICS.csv", index=False, encoding="utf-8")
topic_info.to_csv(OUT_DIR / "SCOTBESS_BERTOPIC_TOPIC_INFO.csv", index=False, encoding="utf-8",)
topic_coverage.to_csv(OUT_DIR / "SCOTBESS_BERTOPIC_TOPIC_COVERAGE.csv", index=False, encoding="utf-8")

topic_model.save(OUT_DIR / "SCOTBESS_BERTOPIC_MODEL", serialization="safetensors", save_ctfidf=True)