In [1]:
import json
import pandas as pd
from collections import defaultdict, Counter
import re

**REVIEWING CATEGORIES THAT WERE FREQUENTLY MISCLASSFIED**

In [ ]:
OUTPUT_CSV = "SCOTBESS_DATASET_MASKED.csv"
ENTITIES_COL = "llm_entities_json"

ENTITY_CATEGORIES = [
    "APPLICATION_CODE",
    "PERSON",
    "ORGANIZATION",
    "PLACE"]

masked_df = pd.read_csv(OUTPUT_CSV)

# value -> Counter({category: number_of_rows_detected})
counts_by_value = defaultdict(Counter)

parse_errors = []

for row_index, raw_output in masked_df[ENTITIES_COL].items():

    if pd.isna(raw_output) or not str(raw_output).strip():
        continue

    try:
        entities = (
            json.loads(raw_output)
            if isinstance(raw_output, str)
            else raw_output)

        for category in ENTITY_CATEGORIES:

            # Do not count the same value twice within one document
            row_values = {
                str(value).strip()
                for value in entities.get(category, [])
                if str(value).strip()}

            for value in row_values:
                counts_by_value[value][category] += 1

    except (json.JSONDecodeError, TypeError, AttributeError) as error:
        parse_errors.append({
            "row_index": row_index,
            "error": str(error),
            "raw_output": raw_output})

print(f"Unique candidate values: {len(counts_by_value)}")
print(f"Rows with parsing errors: {len(parse_errors)}")

Unique candidate values: 2212
Rows with parsing errors: 0

In [ ]:
review_rows = []

for value, category_counts in counts_by_value.items():

    categories = sorted(category_counts.keys())

    review_rows.append({
        "value": value,
        "detection_frequency": sum(category_counts.values()),
        "categories": " | ".join(categories),
        "category_frequencies": " | ".join(
            f"{category}: {category_counts[category]}"
            for category in categories),
        "category_conflict": len(categories) > 1})

candidate_review_df = (
    pd.DataFrame(review_rows).sort_values(
        ["category_conflict", "detection_frequency", "value"],
        ascending=[False, False, True]).reset_index(drop=True))

In [ ]:
conflicts_df = candidate_review_df[candidate_review_df["category_conflict"]].copy()

conflicts_df = candidate_review_df[candidate_review_df["category_conflict"]].copy()
conflicts_df["final_category"] = ""
#exporting for manual review/resolving the overlapping categories
#conflicts_df.to_excel("masking_category_conflicts_review.xlsx",index=False)

display(conflicts_df)

,value,detection_frequency,categories,category_frequencies,category_conflict,final_category
0,Rothienorman,79,PERSON | PLACE,PERSON: 2 | PLACE: 77,True,
1,SSEN,61,ORGANIZATION | PERSON,ORGANIZATION: 60 | PERSON: 1,True,
2,Mey,43,PERSON | PLACE,PERSON: 1 | PLACE: 42,True,
3,Highland Council,28,ORGANIZATION | PERSON | PLACE,ORGANIZATION: 25 | PERSON: 1 | PLACE: 2,True,
4,East Lothian Council,23,ORGANIZATION | PERSON | PLACE,ORGANIZATION: 14 | PERSON: 2 | PLACE: 7,True,
5,Scottish Fire and Rescue Service,21,ORGANIZATION | PERSON,ORGANIZATION: 20 | PERSON: 1,True,
6,Pegasus Group,19,ORGANIZATION | PERSON,ORGANIZATION: 18 | PERSON: 1,True,
7,Cockenzie Storage Limited,15,ORGANIZATION | PERSON,ORGANIZATION: 14 | PERSON: 1,True,
8,Hollandmey,15,ORGANIZATION | PLACE,ORGANIZATION: 1 | PLACE: 14,True,
9,Danestone,11,PERSON | PLACE,PERSON: 1 | PLACE: 10,True,
10,Cockenzie Storage B Limited,9,ORGANIZATION | PERSON,ORGANIZATION: 8 | PERSON: 1,True,
11,Moss Landing Vistra Power Plant,9,ORGANIZATION | PLACE,ORGANIZATION: 1 | PLACE: 8,True,
12,SSE,9,ORGANIZATION | PERSON,ORGANIZATION: 8 | PERSON: 1,True,
13,Scottish Water,9,ORGANIZATION | PERSON,ORGANIZATION: 8 | PERSON: 1,True,
14,APP/2025/1015,8,APPLICATION_CODE | PLACE,APPLICATION_CODE: 7 | PLACE: 1,True,
15,Lewis Grassic Gibbon,8,PERSON | PLACE,PERSON: 7 | PLACE: 1,True,
16,Scottish Government,8,ORGANIZATION | PERSON | PLACE,ORGANIZATION: 6 | PERSON: 1 | PLACE: 1,True,
17,Stonehaven,8,PERSON | PLACE,PERSON: 1 | PLACE: 7,True,
18,Cockenzie Primary School,7,PERSON | PLACE,PERSON: 1 | PLACE: 6,True,
19,Persley,7,PERSON | PLACE,PERSON: 1 | PLACE: 6,True,
20,Zenobe,7,ORGANIZATION | PERSON,ORGANIZATION: 6 | PERSON: 1,True,
21,AAH consulting,6,ORGANIZATION | PERSON,ORGANIZATION: 5 | PERSON: 1,True,
22,Flexpower,6,ORGANIZATION | PERSON,ORGANIZATION: 5 | PERSON: 1,True,
23,GPC 1137 Ltd,6,ORGANIZATION | PLACE,ORGANIZATION: 5 | PLACE: 1,True,
24,Hardgate,6,PERSON | PLACE,PERSON: 1 | PLACE: 5,True,
25,HSE,5,ORGANIZATION | PERSON,ORGANIZATION: 4 | PERSON: 1,True,
26,Leitholm,5,PERSON | PLACE,PERSON: 1 | PLACE: 4,True,
27,RNA Energy,5,ORGANIZATION | PERSON,ORGANIZATION: 4 | PERSON: 1,True,
28,Ben Reid,4,PERSON | PLACE,PERSON: 3 | PLACE: 1,True,
29,Dandara,4,ORGANIZATION | PLACE,ORGANIZATION: 2 | PLACE: 2,True,
30,ECU,4,ORGANIZATION | PERSON,ORGANIZATION: 2 | PERSON: 2,True,
31,AAH,3,ORGANIZATION | PERSON,ORGANIZATION: 2 | PERSON: 1,True,
32,Aberdeen City,3,ORGANIZATION | PLACE,ORGANIZATION: 1 | PLACE: 2,True,
33,Countesswells,3,PERSON | PLACE,PERSON: 1 | PLACE: 2,True,
34,Dewsford Cottage,3,PERSON | PLACE,PERSON: 1 | PLACE: 2,True,
35,Duntocher,3,PERSON | PLACE,PERSON: 1 | PLACE: 2,True,
36,ELC,3,ORGANIZATION | PERSON,ORGANIZATION: 2 | PERSON: 1,True,
37,Hurlie,3,PERSON | PLACE,PERSON: 1 | PLACE: 2,True,
38,OPD Energy,3,ORGANIZATION | PERSON,ORGANIZATION: 2 | PERSON: 1,True,
39,Rigifa,3,ORGANIZATION | PLACE,ORGANIZATION: 1 | PLACE: 2,True,
40,SGN,3,ORGANIZATION | PERSON,ORGANIZATION: 2 | PERSON: 1,True,
41,Backstyles,2,PERSON | PLACE,PERSON: 1 | PLACE: 1,True,
42,Eccles Sub Station,2,PERSON | PLACE,PERSON: 1 | PLACE: 1,True,
43,Field New Deer Ltd,2,ORGANIZATION | PERSON,ORGANIZATION: 1 | PERSON: 1,True,
44,Harbours Medical Practice,2,PERSON | PLACE,PERSON: 1 | PLACE: 1,True,
45,Leylodge Motors,2,PERSON | PLACE,PERSON: 1 | PLACE: 1,True,
46,Lovat Estates,2,ORGANIZATION | PERSON,ORGANIZATION: 1 | PERSON: 1,True,
47,North Leylodge farm,2,PERSON | PLACE,PERSON: 1 | PLACE: 1,True,
48,RES,2,ORGANIZATION | PERSON,ORGANIZATION: 1 | PERSON: 1,True,
49,Robert Gordon’s College,2,ORGANIZATION | PERSON,ORGANIZATION: 1 | PERSON: 1,True,
50,Scottish Fire and Rescue service,2,ORGANIZATION | PLACE,ORGANIZATION: 1 | PLACE: 1,True,
51,The King’s Foundation,2,ORGANIZATION | PERSON,ORGANIZATION: 1 | PERSON: 1,True,

In [5]:
#df with manually resolved overlapping categories
REVIEW_XLSX = "masking_category_conflicts_review.xlsx"

resolved_conflicts = pd.read_excel(REVIEW_XLSX)
resolved_conflicts["final_category"] = (resolved_conflicts["final_category"].fillna("").str.strip().str.upper())
display(resolved_conflicts[["value", "categories", "final_category"]])

,value,categories,final_category
0,Rothienorman,PERSON | PLACE,PLACE
1,SSEN,ORGANIZATION | PERSON,ORGANIZATION
2,Mey,PERSON | PLACE,PLACE
3,Highland Council,ORGANIZATION | PERSON | PLACE,ORGANIZATION
4,East Lothian Council,ORGANIZATION | PERSON | PLACE,ORGANIZATION
5,Scottish Fire and Rescue Service,ORGANIZATION | PERSON,ORGANIZATION
6,Pegasus Group,ORGANIZATION | PERSON,ORGANIZATION
7,Cockenzie Storage Limited,ORGANIZATION | PERSON,ORGANIZATION
8,Hollandmey,ORGANIZATION | PLACE,PLACE
9,Danestone,PERSON | PLACE,PLACE
10,Cockenzie Storage B Limited,ORGANIZATION | PERSON,ORGANIZATION
11,Moss Landing Vistra Power Plant,ORGANIZATION | PLACE,PLACE
12,SSE,ORGANIZATION | PERSON,ORGANIZATION
13,Scottish Water,ORGANIZATION | PERSON,ORGANIZATION
14,APP/2025/1015,APPLICATION_CODE | PLACE,APPLICATION_CODE
15,Lewis Grassic Gibbon,PERSON | PLACE,PLACE
16,Scottish Government,ORGANIZATION | PERSON | PLACE,ORGANIZATION
17,Stonehaven,PERSON | PLACE,PLACE
18,Cockenzie Primary School,PERSON | PLACE,PLACE
19,Persley,PERSON | PLACE,PLACE
20,Zenobe,ORGANIZATION | PERSON,ORGANIZATION
21,AAH consulting,ORGANIZATION | PERSON,ORGANIZATION
22,Flexpower,ORGANIZATION | PERSON,ORGANIZATION
23,GPC 1137 Ltd,ORGANIZATION | PLACE,ORGANIZATION
24,Hardgate,PERSON | PLACE,PLACE
25,HSE,ORGANIZATION | PERSON,ORGANIZATION
26,Leitholm,PERSON | PLACE,PLACE
27,RNA Energy,ORGANIZATION | PERSON,ORGANIZATION
28,Ben Reid,PERSON | PLACE,PERSON
29,Dandara,ORGANIZATION | PLACE,ORGANIZATION
30,ECU,ORGANIZATION | PERSON,ORGANIZATION
31,AAH,ORGANIZATION | PERSON,ORGANIZATION
32,Aberdeen City,ORGANIZATION | PLACE,PLACE
33,Countesswells,PERSON | PLACE,PLACE
34,Dewsford Cottage,PERSON | PLACE,PLACE
35,Duntocher,PERSON | PLACE,PLACE
36,ELC,ORGANIZATION | PERSON,ORGANIZATION
37,Hurlie,PERSON | PLACE,PLACE
38,OPD Energy,ORGANIZATION | PERSON,ORGANIZATION
39,Rigifa,ORGANIZATION | PLACE,ORGANIZATION
40,SGN,ORGANIZATION | PERSON,ORGANIZATION
41,Backstyles,PERSON | PLACE,PLACE
42,Eccles Sub Station,PERSON | PLACE,PLACE
43,Field New Deer Ltd,ORGANIZATION | PERSON,ORGANIZATION
44,Harbours Medical Practice,PERSON | PLACE,PLACE
45,Leylodge Motors,PERSON | PLACE,ORGANIZATION
46,Lovat Estates,ORGANIZATION | PERSON,PLACE
47,North Leylodge farm,PERSON | PLACE,PLACE
48,RES,ORGANIZATION | PERSON,ORGANIZATION
49,Robert Gordon’s College,ORGANIZATION | PERSON,PLACE
50,Scottish Fire and Rescue service,ORGANIZATION | PLACE,ORGANIZATION
51,The King’s Foundation,ORGANIZATION | PERSON,ORGANIZATION

In [6]:
conflict_resolutions = dict(zip(resolved_conflicts["value"], resolved_conflicts["final_category"]))

In [ ]:
ENTITY_CATEGORIES = [
    "APPLICATION_CODE",
    "PERSON",
    "ORGANIZATION",
    "PLACE"]
#the llm struggled with detecting the entities, eg. it masked "Aberdeen" in one representation but not the next one
#so the above defined categories will be converted into sets and detected globally, to increase recall
#other categries (email, phone, link) will be resolved on project (row) level, as they are unambiguous

candidate_sets = {
    category: set()
    for category in ENTITY_CATEGORIES}

for _, row in candidate_review_df.iterrows():
    value = row["value"]

    if bool(row["category_conflict"]):
        final_category = conflict_resolutions.get(value, "")
    else:
        #non-conflicting candidates keep their original category
        final_category = row["categories"]

    if final_category == "REJECT":
        continue

    if final_category not in candidate_sets:
        raise ValueError(
            f"Missing or invalid category for {value!r}: "
            f"{final_category!r}")

    candidate_sets[final_category].add(value)

In [8]:
APPLICATION_CODE_SET = candidate_sets["APPLICATION_CODE"]
PERSON_SET = candidate_sets["PERSON"]
ORGANIZATION_SET = candidate_sets["ORGANIZATION"]
PLACE_SET = candidate_sets["PLACE"]

for category, values in candidate_sets.items():
    print(f"{category}: {len(values)} unique candidates")

APPLICATION_CODE: 149 unique candidates
PERSON: 211 unique candidates
ORGANIZATION: 345 unique candidates
PLACE: 1507 unique candidates

In [9]:
#for inspection
for category, values in candidate_sets.items():
    print(f"\n--- {category} ---")

    for value in sorted(values, key=str.casefold):
        print(repr(value))

--- APPLICATION_CODE ---
'00004838'
'100655885- 001'
'100711077-001'
'13/0479/FUL'
'15/03392/FUL'
'19/01861/S36'
'19/05385/FUL'
'20/02823/PAN'
'20/9004/PREAPP'
'2023/0378/TP'
'2024/0168/TP'
'202400433145'
'21/00047 EIASCR'
'21/01348/SCR'
'21/02985/FUL'
'21/03353/FUL'
'21/03553/FUL'
'21/05467/FUL'
'21/05536/FUL'
'22/00601/FUL'
'22/01416/AMM'
'22/01485/PAN'
'22/02054/FUL'
'22/03638/FUL'
'23/0001/EAA'
'23/0004/S36'
'23/00862'
'23/01113/FUL'
'23/0113/FUL'
'23/03113/FUL'
'23/03113/Full Development'
'23/04100/FUL'
'23/05905/FUL'
'231192/PREAPP'
'231480/ESC'
'24/00561/FUL'
'24/00765'
'24/01489/FUL'
'24/01548/FUL'
'24/02621/S36'
'24/0264/FUL'
'24/02641/FUL'
'24/02655/SCOP'
'24/02831/FUL'
'24/03064/SCOP'
'24/05255/S36'
'24/1531/S36'
'240614/DPP'
'240791/S36'
'241074/S36'
'241197-05'
'241197-09'
'241197-12'
'241197/DPP'
'25/00107/FUL'
'25/00307/S36'
'25/00498/S36'
'25/00503/S36'
'25/02382/S36'
'A and B'
'APP/2020/1437'
'APP/2020/1673'
'APP/2021/0936'
'APP/2022/0249'
'APP/2022/0651'
'APP/2022/1218'
'APP/2022/2007'
'APP/2022/2022'
'APP/2022/2676'
'APP/2023/0718'
'APP/2023/0940'
'APP/2023/1017'
'APP/2023/2310'
'APP/2024/1604'
'APP/2024/1812'
'APP/2024/1951'
'APP/2024/2066'
'APP/2024/2125'
'APP/2025/0089'
'APP/2025/0313'
'APP/2025/0415'
'APP/2025/1015'
'APP/2025/1673'
'APP/22/2252'
'APP/22/252'
'APPP/2023/0718'
'APR 527952'
'B'
'ECU 00005162'
'ECU ref 4749'
'Ecu00002167'
'ECU00003326'
'ECU00003354'
'ECU00003361'
'ECU00003469'
'ECU00004601'
'ECU00004659'
'ECU00004804'
'ECU00004838'
'ECU00004851'
'ECU00004872'
'ECU00004881'
'ECU00004907'
'ECU00004926'
'ECU00004941'
'ECU00004963'
'ECU00004968'
'ECU00004969'
'ECU00004986'
'ECU00004993'
'ECU00005049'
'ECU00005113'
'ECU00005116'
'ECU00005155'
'ECU00005160'
'ECU00005162'
'ECU00005166'
'ECU00005224'
'ECU00005233'
'ECU00006022'
'ECU00006053'
'ECU00006067'
'ECU00006121'
'ECU00006204'
'ECU0005160'
'ECUOOOO5113'
'EN010106'
'ENQ/2020/1884'
'ENQ/2022/1473'
'ENQ/2023/0351'
'ENQ/2024/0415'
'ENQ/2024/0747'
'ENQ/2024/0934'
'ENQ/2024/1397'
'ENQ/2024/1516'
'ENQ/2025/0256'
'ENQ/2025/0509'
'GPC 013 Ltd'
'HOLLANDMEY RENEWABLE ENERGY DEVELOPMENT'
'NL008500079'
'NLMW1172'
'P.130490'
'P/22/0472'
'PAC1'
'PPA-270-2117'
'ref C2'
'ref C5'
'SG-RFQ-2024022'
'UCU Ref 00005233'

--- PERSON ---
'3 Lynn Drive'
'a fireman friend'
'a fraser'
'A J and Mrs H Urquhart'
'a local resident and father of young children'
'A M Alexander'
'a resident of the Beauly area'
'a retired engineer'
'Agnes David withers'
'All other councillors'
'Amit Gudka'
'Andy Hayton'
'Angus Council'
'Anna Clark'
'Arran View'
'Aude Chaiban'
'Barry Steele'
'Ben Reid'
'C. L. Martin PHD'
'Chariperson'
'Chris Calvert'
'Colin MacFarlane'
'Conrad Energy'
'Councillor'
'councillors'
'Craig MacCormick'
'D and Mrs A MacCormick'
'Dame Maria Miller MP'
'danestone community council'
'Dave Doogan MP'
'David Cowan'
'David Skene'
'Diane French'
'Doctor of Physics'
'Donald Shaw'
'Douglas McAllister'
'Douglas Ross'
'Dr Alison Bruce'
'Dr Ben MacGregor'
'Dr K.Brophy'
"Eaglesham's Conservation Village status"
'East Caplaw'
'Elaine Ryan'
'Euan Glen'
'Faifley resident'
'Field Rigifa'
'Fiona MacCormick'
'Fire Scotland'
'Fire Service'
'Frank Tindall'
'Frankly'
'Gail Beattie'
'Gary Forsyth'
'Gary McIlravey'
'Gatehead Farm'
'George Arnold'
'Georgina Coburn'
'Gillian Martin'
'Glenn Church'
'Gordon Hughes'
'Gordon Milligan'
'Gwendolyn Pirie'
'H. Curran'
'Harris'
"Has the Badger's Trust"
'Head of planning East Ayrshire'
'Helen'
'High School'
'HM Queen Elizabeth the Queen Mother'
'I'
'I, Simon Sawers'
'Iain Wilkie'
'Ian Currums'
'Ian Kelly'
'Ian Kelly MRTPI'
'Ian Sharp'
'J. Smith'
'Jackson Carlaw'
'James Black'
'Jamie Stone'
'Jane Lassey'
'Janette Lawler'
'Jean Clasper'
'Jim Cruickshank'
'Joan MacKenzie'
'John & Elaine Ryan'
'John Bey'
'John Fannon'
'John Irvine'
'John Kent'
'John McIntosh'
'Johnnie Cope'
'Julie Rees-Field'
'K and C Bethune'
'Kathrin Haltiner'
'Kay King'
'Lee-Anne Munro'
'Lewis Grassick Gibbon'
'Leylodge Against industrialisation'
'Liam MacLeod'
'Liz Lake'
'local councillors'
'local farmers'
'local MP'
'local MSP'
'Logan PM'
'Lord Advocate'
'Lord Lovat'
'Lyn Jardine'
'Margaret Cruickshank'
'Martin Worth'
'mine'
'MISS CAROLINE MACRAE'
'MISS DEMI SIMPSON'
'Mr & Mrs Campbell McNab'
'Mr and Mrs Riddell'
'Mr and Mrs Stewart'
'Mr Andrew Bruce'
'Mr Eion Gibbs'
'Mr John Farquhar'
'Mr R'
'Mr. Ramsay'
'Mrs A MacCormick'
'Mrs Dawn Kirkwood'
'Mrs Doolan'
'Mrs June Ewan'
'Mrs Kay King'
'Mrs Teresa Shaw'
'MS EILEEN MCMILLAN'
'Ms McFadzean'
'mScottish Fire and Rescue'
'MSP'
'Muriel Beattie'
'my'
'my daughter'
'My eldest child'
'My eldest son'
'my family'
'my family members'
'my family’s'
'My father'
'my husband'
'my late husband'
'my livestock and pets'
'my mother'
'my mother-in-law'
'My mum'
'my neighbours'
'my son'
'My son'
'my two really young kids'
'My understanding is that National Planning Framework 4 addresses the need for Cumulative Impact to be considered. This development, if approved, would be in a field adjacent to the Zenobe development which has already been approved and close to the other developments mentioned above. Further development in this area will change our environment out of all recognition.'
'My wife'
'my wife and I'
'my young children'
'my youngest child'
'myself'
'N. Bolan'
'Neil Malcolm'
'Neil Parish'
'Neil Sinclair'
'Our Client'
'our friends'
'Our Local MP'
'Our two young children'
'Paul Christensen'
'Paul McLennan'
'Phillips'
'Police Scotland'
'Prof. Xavier Lambin'
'Professor (Emeritus) PJ Dobson OBE'
'Professor (Emeritus) PP Edwards FRS'
'Professor Dobson'
'Professor Edwards'
'Queen Mother'
'Rankl F'
'Redacted'
'Richard Palmer'
'Richard Sharland'
'Righead'
'Robert Gordon'
'Rowanhill'
'Rowe G'
'Ryan Currie'
'S SIMEC Atlantis Energy (SAE) Renewables'
'S Smith'
'Scott Hobbs'
'Senior Pastor'
'several pets'
'Simkins G'
'Simon Lovat'
'Socially Conscious Capital'
'Stephen Fraser'
'Stephen Welsh'
'Syd Marwick'
'Teresa'
'The Beauly Fishing Syndicate'
'the British Trust for Ornithology'
'The hon Graeme Steel'
'The local MP'
'the original farmer'
'the three councillors'
'The two community councils'
'Tim Barratt'
'Tina Marshall'
'Tom Morrison'
'Vhari Cairns'
'W. Curran'
'Walker A'
'Wemyss and March Estates'
'xxxxxx'

--- ORGANIZATION ---
'AAH'
'AAH Consultants'
'AAH consulting'
'ABEI Energy'
'ABEI Energy Group'
'Aberdeen & Grampian Chamber of Commerce'
'Aberdeen City Council'
'Aberdeenshire Council'
'Aberdeenshire council'
'Aberdeenshire Council Committee'
'Aberdeenshire Council Planning and Environmental Services Stonehaven'
'Aberdeenshire Council Planning Authority'
'ACC'
'AEUK Battery Project II'
'Alcemi'
'Amb Clean'
'AMP Clean Energy'
'Anesco'
'Angus Resilience Partnership'
'Apatura'
'Apatura (GPC 013 Ltd)'
'Apatura Energy'
'ASC'
'Aspect Landscape Planning Ltd'
'Atmos Consulting Ltd'
'Auldearn Community Council'
'Badger Trust'
'Balnacraig Battery Storage Ltd'
'Bat Conservation Trust'
'BBC Bitesize'
'Bennachie Community Council'
'Berwick Bank Wind Farm'
'BESS'
'Blackford Energy'
'Blackford Energy Ltd'
'Blackford Renewables'
'Blackford Renewables Ltd'
'Bluestone Energy'
'Braidfield Battery Storage'
'Branxton Energy Storage Facility'
'Branxton PV & BESS'
'Braston Farm New energy'
'Braston New Energy'
'British Trust for Ornithology'
'Bt?'
'BTO'
'Buccleuch'
'Buchanan Holding company'
'Buchanan Orthotics Limited'
'Buglife Scotland'
'Caithness Bird Club'
'Caithness Bird Clubs'
'Caithness Heath Action Team'
'CALA homes'
'Caledonia Offshore Wind Farm Limited'
'Clean Energy Associates (CEA)'
'Clydesdale Harriers'
'Cockenzie & Port Seton Community Council Committee'
'Cockenzie B Ltd'
'Cockenzie storage B limited'
'Cockenzie Storage B Limited'
'Cockenzie Storage B Ltd'
'Cockenzie Storage Limited'
'Cockenzie Storage limited'
'Cockenzie Storage Ltd'
'COGEO'
'Community Council'
'Company'
'COPE Ltd'
'Creich Community Council'
'Crystal Rig Solar'
'Dalgety Skip Hire'
'Dandara'
'DANESTONE CONGREGATIONAL CHURCH'
'DEFRA'
'Department for Energy Security & Net Zero'
'Developer'
'Deveron, Bogie and Isla Rivers Charitable trust'
'DPEA'
'Drinking Water Quality Regulator for Scotland (DWQR)'
'Dundee City Council'
'DWP'
'East Lothian council'
'East Lothian Council'
'East Renfrewshire Council'
'east Renfrewshire council'
'East Renfrewshire Council (ERC)'
'EastCoastGridServices Ltd.'
'Eccles Energy Centre'
'ECU'
'ELC'
'Electric Power Research Institute'
'Electric Power Research Institute (EPRI)'
'electricity generating company'
'Energiekontor'
'Energy Consents Unit'
'Energy Safety Response Group'
'Energy Workshops'
'Environment Agency/SEPA'
'Equinor/Noriker'
'ERC'
'ERC Committee'
'Estover Energy'
'European Chemicals Agency'
'Faversham Society'
'FCC'
'Field'
'Field Beauly'
'FIELD BESS'
'Field Corriemoillie Ltd'
'Field Developers'
'Field Energy'
'Field Ltd'
'Field New Deer Ltd'
'Field Rigifa Ltd'
'Fife Council'
'FlexPower'
'Flexpower'
'Forest and Land Scotland'
'Fort Augustus & Glenmoriston Community Council'
'Foundation Scotland'
'Galileo Technical Response'
'Genre'
'Glasgow City Council'
'Go Glamping Loch Ness'
'Govan CC'
'Govan Community Council'
'GP PLANNING LTD'
'GP Planning Ltd'
'GPC 1137 Ltd'
'GPC 676'
'GPC 680'
'GPC1137 Ltd'
'Grampian Housing'
'Grampian Packaging Supplies'
'Green Switch'
'Green Switch Capital'
'Green Switch Capital (GSC) Dalchork Limited'
'Green Switch Capital Dalchork Ltd'
'Green Switch Capital Ltd'
'Greenspan’s Planning'
'Greenswitch Capital Limited'
'Gresham'
'Gresham House'
'GRP'
'GSC Middleton of Potterton Limited'
'GSC MIDDLETON OF POTTERTON LIMITED'
'Health & Safety Executive'
'Health and Safety Executive'
'Health and Safety Executive (HSE)'
'Helix Robotics Solutions Ltd'
'Helix Well Ops (UK) Ltd'
'Herbert Smith Freehills'
'Highland Council'
'Highland Raptor Study Group'
'Historic Environment Scotland'
'House of Commons Library'
'HSE'
'Ian Sharland Ltd'
'ICE'
'IGP Solar 25 Limited'
'ILI Group'
'ILI Ltd'
'Inshes & Milton of Leys CC (I&MoLCC)'
'Inshes & Milton of Leys Community Council'
'Intelligent Land Investments'
'Intelligent Land Investments Group plc'
'Intergen'
'Inverclyde Council'
'Inverness Caledonian Thistle'
'Inverness Caledonian Thistle football club'
'Inverness Fire Service'
'Invinity Energy'
'Invinity Energy Systems'
'Island Green Power'
'Kaimes Renewable Energy Park'
'Kilmacolm Civic Trust'
'Kilmacolm Community Council'
'Kilmorack Community Council'
'Kilmorack Gallery'
'Kirkhill and Bunchrew Community Council'
'Kirkwood Homes'
'Laister Planning Ltd'
'Land Use Consultants'
'Leiths'
'Leylodge Motors'
'Liz Lake Associates'
'Locogen Consulting Ltd'
'Lothian Building Preservation Trust'
'LS Power'
'Merseyside Fire and Rescue (MFRS)'
'Moirs Construction'
'Momentum Transport Consultancy'
'Moyes Farms Limited'
'NAC'
'National Fire Chief Council'
'National Fire Chiefs Council'
'National Fire Chiefs Council (NFCC)'
'National Fire Protection Association'
'National Fire Safety Services (Ltd)'
'National Fire Safety Services Ltd'
'National Grid'
'National Grid (now NESO)'
'National Grid ESO'
'National Institute for Occupational Safety and Health (NIOSH)'
'Natural Scottish Heritage'
'Nature Scot'
'NatureScot'
'NESO'
'Network Rail'
'NFCC'
'NHS Health Scotland'
'NHS Tayside'
'North Yorkshire fire service'
'NRCC'
'Ofgem'
'Omexon'
'OPD'
'OPD Energy'
'Opdenergy'
'Paceconsult'
'Pacific Northwest National Laboratory'
'Peak Well Systems'
'Pegasus'
'PEGASUS GROUP'
'Pegasus Group'
'Pegasus Group Ltd'
'Peterhead Fire Service'
'Peterhead Fire Station'
'Planning Service'
'Quair Renewables UK Limited'
'R&D Ecology'
'RE Projects Development Ltd'
'Regen'
'Renewable Connections'
'RES'
'RES (formerly Renewable Energy Systems Ltd)'
'RES (Renewable Energy Systems)'
'Resilience water project'
'Rigifa'
'RNA Energy'
'RNA-Energy Ltd'
'Roberts Highway Consultants'
'RPS Group'
'RSPB'
'RSPB Scotland'
'Salters Battery Storage Limited'
'Save Shetland'
'Scala Renewables'
'ScotGov'
'Scotland Fire & Rescue Service'
'Scott Hobbs Planning'
'Scottish & Southern Electricity Networks (SSEN)'
'Scottish and Southern Electricity Networks'
'Scottish and Southern Electricity Networks (SSEN)'
'Scottish Badgers'
'Scottish Borders Council'
'Scottish CAF'
'Scottish Environment Protection Agency'
'Scottish Environmental Protection Agency'
'Scottish Environmental Protection Agency (SEPA)'
'Scottish Fire'
'Scottish Fire & Rescue'
'Scottish Fire & Rescue Service'
'Scottish Fire & Rescue Service (SFRS)'
'Scottish Fire and Rescue (SFRS)'
'Scottish Fire and Rescue service'
'Scottish Fire and Rescue Service'
'Scottish Fire and Rescue Service (SFRS)'
'Scottish Fire Brigade'
'Scottish Fire Service'
'Scottish Forestry'
'Scottish Gas'
'Scottish Gas Network'
'Scottish Gas Networks'
'Scottish Government'
'Scottish Government Energy Consents Unit'
"Scottish Government's Energy Consents Unit"
'Scottish Government’s Energy Consents Unit'
'Scottish Hydro Electric Power Distribution (SHEPD)'
'Scottish Hydro Electric Power Distribution plc'
'Scottish Hydro Electric Transmission'
'Scottish Hydro Electric Transmission plc'
'Scottish National Library'
'Scottish Natural Heritage'
'Scottish Planning Policy (SPP)'
'Scottish Power'
'Scottish power'
'Scottish Power Energy Network'
'Scottish Power Energy Networks'
'Scottish Power Energy Networks (SPEN)'
'Scottish Power Renewables'
'Scottish Renewables'
'Scottish Water'
'Scotways'
'Seagreen 1a Limited'
'SEPA'
'SEPA (Scottish Environment Protection Agency)'
'SFRS'
'SGN'
'Shetland Charitable Trust'
'SIMEC Atlantis Energy (SAE) Renewables'
'Sirius EcoDev (Tealing) Ltd'
'Solar Energy UK'
'Source Galileo'
'South Lanarkshire Council'
'Southern Electric Power Distribution plc'
'SP Energy Networks'
'SPT'
'SSE'
'SSEN'
'SSEN Distribution and Transmission'
'SSEN Transmission'
'Statera Energy'
'Statkraft UK Ltd'
'Strathgryfe Angling Association (SAA)'
'Tesco'
'THC'
'the Aberdeenshire Council'
'The Applicant'
"the Badger's Trust"
'The Highland Council'
'The Institution of Gas Engineers'
'The Inverness Courier'
'The King’s Foundation'
'the local group'
'The Scottish Government'
'The Trust'
'This company'
'Tina Marshall Consultancy Ltd.'
'Transport Scotland'
'Tyne and Wear Fire & Rescue Service'
'UK House of Commons Library'
'UK Infrastructure Planning Inspectorate'
'Virmati Energy Ltd'
'Vistra Energy'
'Weaver Power'
'West Dunbartonshire Council'
'Whirlwind Energy Storage Limited'
'Whirlwind Renewables LLP'
'Woodland Trust'
'Yorkshire Fire Brigade'
'Yorkshire fire brigade'
'Zenobe'
'Zenobe Energy Limited'

--- PLACE ---
'10 Birnieknowes Cottages'
'13raidfield Farm'
'14 Blackford Avenue'
'17 Acres'
'19 Culburnie'
'21 Ruisaurie'
'24 westhall terrace murroes by duntrune dundee dd40sn'
'325M SW of Torrdhuin, Auchterawe, Fort Augustus'
'340MW battery storage'
'42 Malcolms Way Stonehaven AB39 2ST'
'49.9MW'
'50 Cedar Drive, Port Seton. EH32 0SN'
'53 Brackenrig crec Waterfoot'
'54 Barlae Avenue'
'55 Vastern Road Reading Berkshire RG1 8BU'
'6 Panmure Way'
'8 Rowanhill Drive, Port Seton, EH32 0SW'
'82 major road'
'9a Millgate Friockheim DD11 4TW'
'a B classified road'
'a forest'
'a large quarry'
'a lively area'
'a plethora of pylons'
'a police station'
'a pond'
'a power station and dam'
'a productive salmon river'
'a single fence'
'a small village community'
'a substation'
'a very nice area'
'a very nice village'
'a water course'
'a wedding venue'
'a wind farm'
'A1'
'A1 Bypass'
'A199'
'A713'
'A720 City Bypass'
'A726'
'A737'
'A77'
'A77 road'
'A78'
'A809'
'A810'
'A82'
'A831'
'A832'
'A832 NC500 tourist route'
'A835'
'A835 truck road'
'A836'
'A9'
'A90'
'A90/AWPR'
'A92 Parkway'
'A920'
'A939'
'A947'
'A96'
'A96 Trunk Road'
'A96T'
'AB21 7AN'
'AB21 7AP'
'AB22 8AQ'
'AB23 8YX'
'AB30 1LR'
'AB39'
'AB39 2XT'
'AB42 3JP'
'AB51 5BL'
'AB51 8YN'
'Aberdeen'
'Aberdeen AB15 7AL'
'Aberdeen city'
'Aberdeen City'
'Aberdeen City Greenbelt'
'Aberdeen Infirmary'
'Aberdeen International Airport'
'Aberdeenshire'
'Aberdeenshire AB30 1LR'
'Aberlady nature reserve'
'Achalone'
'Achanarras'
'Achanarras burn'
'Achies'
'Achlachlan'
'Achnasheen'
'Achvraid House'
'Aigas'
'airyhall'
'Airyhall Electricity Depot'
'Albion Car park'
'Albion carpark'
'Alness substation'
'Altens industrial estate'
'Altnabreach'
'Altyre'
'An Cabar'
'an extremely busy roundabout'
'Ancient Woodland'
'Anderson Drive'
'Angus'
'Antonine Wall'
'Antonine wall'
'Arbuthnot'
'Arbuthnott'
'Ardersier'
'Ardochrig'
'Arisaig, Cochno Road'
'Arizona'
'Aryburn'
'Aryburn Farm'
'Aryburn farm'
'Auchentiber'
'Auchentiber Road'
'Auchmill Road'
'Auchnacraig Countryside Park'
'Auchnacraig Woodland Park'
'Auchterawe'
'Auchterawe sub station'
'Auldearn'
'Aurs Rd'
'Aurs Road'
'Aurs road'
'AWPR'
'Ayr Hospital'
'Ayre Substation'
'Ayrshire'
'Ayrshire Coast'
'B 767'
'B714'
'B767'
'B767 from Eaglesham to the Belle Craig Roundabout'
'B767 Glasgow Road'
'B9101'
'B9111'
'B977'
'B992'
'B999'
'Backstyles'
'Baikiehill road'
'Baillie'
'Balbalir Quarry'
'Balblair'
'Balblair Quarry'
'Balblair Sub-station'
'Balblair Substation'
'Balblair substation'
'Ballach'
'Ballach Wind Farm'
'Balnuith'
'Balnuith Cottage'
'Balnuith Farm'
'Banff'
'Banffshire'
'Bankfield Roundabout'
'Bankies Trek'
'Bankpark Brae'
'Bankpark Grange'
'Bankton'
'Bankton House'
'Bankton House & doocot'
'Bannatyne Health Centre'
'Banniskirk'
'Banniskirk Substation'
'Banshed Moss'
'Barlae Avenue'
'Barlae Avenue G76 0DA'
'Barnhill Road'
'Barns Ness Terrace (C121)'
'Barnwell / Wright Street'
'Barras'
'Barras area'
'Barras Stonehaven'
'Barrhead'
'Barrock'
'Bathgate'
'Bearsden'
'Beauly'
'Beauly -Cannich road'
'Beauly electrical substation'
'Beauly Firth'
'Beauly Firth Ramsar Site'
'Beauly Primary'
'Beauly Priory'
'Beauly River'
'Beauly substation'
'Beijing, China'
'Beinn Dearg'
'BELDAVIE'
'Bell craig roundabout'
'Bell Craig roundabout'
'Belladrum'
'Bellahouston Park'
'Bellahouston park'
'Bellcraig roundabout'
'Bellcraig Roundabout'
'Belle Craig'
'Belle Craig Roundabout'
'Belle Craig roundabout'
'Bellecraig roundabout'
'Bellecraig Roundabout'
'Bellfield'
'Belton House'
'Belton Livery'
'Ben Lomond'
'Ben Reid garden centre'
'Ben Wyvis'
'Ben Wyvis National Nature Reserve'
'Ben Wyvis Special Protection Area'
'Bennachie'
'BerryHill, Fowlis'
'Bervie water'
'Berwick Bank'
'Berwick Bank Eastern Link Branxton Sub Station'
'Berwick on Tweed'
'BESS Dunballoch Farm'
'Bhlaraidh windfarm'
'Bilsdean'
'Birgham'
'Birkenhills'
'Birnieknowes'
'Birnieknowes hamlet'
'Bishops Dal'
'Bishops Dall'
'Blablair'
'Black Bridge'
'Black Burn'
'Black Burn water course'
'Black Isle'
'Blackdog'
'Blackdog substation'
'Blackdyke Farm'
'blackford'
'Blackford'
'Blackford Energy Park'
'Blackford road'
'Blackford Rothienorman'
'Blackford Substation'
'Blackford Woods'
'Blackford, Aberdeenshire'
'Blackford/Fisherford/Rothienorman'
'Blackhill Wood'
'Blackhill woodland'
'Blackhillock'
'Blackhills'
'Blackhills Burn'
'Blackhills Quarry'
'Blackhills, Peterhead'
'Blackpark Farm Nairn'
'Blindwells'
'Bogfern Farm'
'Bower'
'Bowerhouse'
'Bowling'
'Boydston Road'
'Bradfield Farm'
'Braehead'
'Braehead Farm'
'Braidfield'
'Braidfield Farm'
'braidfield park'
'Braidfield Road'
'Braidwood'
'Braidwood Burn'
'Branxton'
'Braston Farm'
'Braxbess'
'Brickworks Road'
'Bridge of Don'
'Bridgend'
'Bridgend Burn'
'Bridgend Farm'
'Bridgend Farm, Arbuthnott'
'Bridgend Mill'
'Broallan'
'Broomloan Road'
'Broubster Leans'
'Bruxie Hill'
'Buccleuch Estate’s land'
'Buckie'
'Bucksburn'
'Bunchrew'
'Burdiehouse Burn'
'Burdiehouse Square'
'Burn of Asleid'
'Burn of Balquholly'
'Burn of Horsegrow'
'Burnbrae Street'
'Busby'
'busy roads'
'Butterywells Farm'
'C1033'
'C120 Birnieknowes Road'
'C1C'
'C1s'
'C26s ( Cuminestown to Fyvie road)'
'C26S Cuminestown- Fyvie road'
'C53'
'c53'
'C53 Boydstone Road'
'C53/Treeswoodhead Road'
'Cabrich'
'Cairdshill'
'Cairngorms'
'Caithness'
'Caithness Lochs'
'Caithness Lochs SPA'
'Caithness Lochs SPA/Ramsar site'
'Calderwood Lodge'
'Caledonian Stadium'
'California'
'Campsie Hills'
'Camsiscan Farm'
'Camus House Inverness'
'Canisbay'
'Canmore (National Record of the historic environment) ID ref.: 105482'
'Canmore ref: 105482'
'Cannich'
'Carn Fearna'
'Carn Gorm'
'Carnegie Road'
'Carnegie road'

In [10]:
#moving misplaced entities
CODE_TO_ORGANIZATION = {
    'HOLLANDMEY RENEWABLE ENERGY DEVELOPMENT'}

ORGANIZATION_SET.update(CODE_TO_ORGANIZATION)
APPLICATION_CODE_SET.difference_update(CODE_TO_ORGANIZATION)


ORGANIZATION_TO_PLACE = {
'Berwick Bank Wind Farm',
'Kaimes Renewable Energy Park'}

PLACE_SET.update(ORGANIZATION_TO_PLACE)


PERSON_TO_PLACE = ({
'3 Lynn Drive',
'Arran View',
'Glenn Church',
'Gatehead Farm'})

PERSON_TO_ORGANIZATION = ({
'Angus Council',
'Conrad Energy',
'danestone community council',
'Fire Service',
'Fire Scotland',
'Socially Conscious Capital',
'The Beauly Fishing Syndicate',
'the British Trust for Ornithology'})

PLACE_SET.update(PERSON_TO_PLACE)
ORGANIZATION_SET.update(PERSON_TO_ORGANIZATION)


PLACE_TO_ORGANIZATION = ({
    'Department for Energy Security and Net Zero'})

ORGANIZATION_SET.update(PLACE_TO_ORGANIZATION)

In [ ]:
#removing overdetected entities and reassigning misclassified entities
ORGANIZATION_SET.difference_update({
'Badger Trust',
'Bat Conservation Trust',
'BESS',
'Berwick Bank Wind Farm',
'British Trust for Ornithology',
'Buccleuch',
'Buglife Scotland',
'Caithness Bird Club',
'Caithness Bird Clubs',
'Caithness Heath Action Team',
'CALA homes',
'Clean Energy Associates (CEA)',
'Community Council',
'Company',
'Developer',
'Department for Energy Security & Net Zero',
'Drinking Water Quality Regulator for Scotland (DWQR)',
'ECU',
'Electric Power Research Institute',
'Electric Power Research Institute (EPRI)',
'electricity generating company',
'Energy Consents Unit',
'Energy Safety Response Group',
'Energy Workshops',
'European Chemicals Agency',
'Forest and Land Scotland',
'Foundation Scotland',
'Fire Scotland',
'Kaimes Renewable Energy Park',
'National Fire Chief Council',
'National Fire Chiefs Council',
'National Fire Chiefs Council (NFCC)',
'National Fire Protection Association',
'National Fire Safety Services (Ltd)',
'National Fire Safety Services Ltd',
'National Grid',
'National Grid (now NESO)',
'National Grid ESO',
'National Institute for Occupational Safety and Health (NIOSH)',
'Natural Scottish Heritage',
'Nature Scot',
'NatureScot',
'Network Rail',
'NHS Health Scotland',
'Planning Service',
'Scottish Badgers',
'Scottish Environment Protection Agency',
'Scottish Environmental Protection Agency',
'Scottish Environmental Protection Agency (SEPA)',
'Scottish Fire',
'Scottish Fire & Rescue',
'Scottish Fire & Rescue Service',
'Scottish Fire & Rescue Service (SFRS)',
'Scottish Fire and Rescue (SFRS)',
'Scottish Fire and Rescue Service',
'Scottish Fire and Rescue service',
'Scottish Fire and Rescue Service (SFRS)',
'Scottish Fire Brigade',
'Scottish Fire Service',
'Scottish Forestry',
'Scottish Gas',
'Scottish Gas Network',
'Scottish Gas Networks',
'Scottish Government',
'Scottish Government Energy Consents Unit',
"Scottish Government's Energy Consents Unit",
'Scottish Government’s Energy Consents Unit',
'Scottish Hydro Electric Power Distribution (SHEPD)',
'Scottish Hydro Electric Power Distribution plc',
'Scottish Hydro Electric Transmission',
'Scottish Hydro Electric Transmission plc',
'Scottish National Library',
'Scottish Natural Heritage',
'Scottish Planning Policy (SPP)',
'Scottish power',
'Scottish Power',
'Scottish Power Energy Network',
'Scottish Power Energy Networks',
'Scottish Power Energy Networks (SPEN)',
'Scottish Power Renewables',
'Scottish Renewables',
'Scottish Water',
'SEPA',
'SEPA (Scottish Environment Protection Agency)',
'The Applicant',
"the Badger's Trust",
'the local group',
'The Scottish Government',
'The Trust',
'This company',
'UK House of Commons Library',
'UK Infrastructure Planning Inspectorate',
})

In [12]:
APPLICATION_CODE_SET.difference_update({
    'B',
    'A and B',
    'ref C2',
    'ref C5'})

In [13]:
PERSON_SET.difference_update({
'3 Lynn Drive',
'a fireman friend',
'a fraser',
'a local resident and father of young children',
'a resident of the Beauly area',
'a retired engineer',
'All other councillors',
'Angus Council',
'Arran View',
'Conrad Energy',
'Councillor',
'councillors',
'danestone community council',
'Doctor of Physics',
"Eaglesham's Conservation Village status",
'Frankly',
'Gatehead Farm',
'Glenn Church',
"Has the Badger's Trust",
'High School',
'HM Queen Elizabeth the Queen Mother',
'I',
'local councillors',
'local farmers',
'local MP',
'local MSP',
'mine',
'my',
'MSP',
'my daughter',
'My eldest child',
'My eldest son',
'my family',
'my family members',
'my family’s',
'My father',
'my husband',
'my late husband',
'my livestock and pets',
'my mother',
'my mother-in-law',
'My mum',
'my neighbours',
'my son',
'My son',
'my two really young kids',
'My understanding is that National Planning Framework 4 addresses the need for Cumulative Impact to be considered. This development, if approved, would be in a field adjacent to the Zenobe development which has already been approved and close to the other developments mentioned above. Further development in this area will change our environment out of all recognition.',
'My wife',
'my wife and I',
'my young children',
'my youngest child',
'myself',
'Our Client',
'our friends',
'Our Local MP',
'Our two young children',
'Phillips',
'Police Scotland',
'Queen Mother',
'S SIMEC Atlantis Energy (SAE) Renewables',
'Senior Pastor',
'several pets',
'Socially Conscious Capital',
'The Beauly Fishing Syndicate',
'the British Trust for Ornithology',
'The local MP',
'the original farmer',
'the three councillors',
'The two community councils',
})

In [ ]:
PLACE_SET.difference_update({
'a large quarry',
'a lively area',
'a plethora of pylons',
'a police station',
'a pond',
'a power station and dam',
'a productive salmon river',
'a single fence',
'a small village community',
'a substation',
'a very nice area',
'a very nice village',
'a water course',
'a wedding venue',
'a wind farm',
'an extremely busy roundabout',
'Ancient Woodland',
'childrens play park',
'children’s play park',
'Community Centre',
'conservation village',
'Conservation Village',
'Conservation village',
'Department for Energy Security and Net Zero',
'doctors',
'doctors surgery',
'Doctors Surgery',
'European landscape convention',
'Fig. 1',
'Fig. 2',
'former coal plant',
'Greenbelt',
'Green Belt',
'Grid Stability Facility',
'grounds',
'historic sites',
'local children’s primary school',
'local nature reserve',
'local nursing home',
'local primary and nursery schools',
'local primary school',
'local residential area',
'motorway',
'my land',
'my neighbourhood',
'my own croft',
'my property and horse stables',
'nearby river',
'nearby school playing fields',
'nearby watercourses',
'nearby woodland',
'nearest an and e',
'nearest fire station',
'new housing development',
'new road',
'nursery',
'old coal store area',
'old power station site',
'our beautiful village',
'our small single track road',
'our village',
'our villiage',
'overlooking properties',
'play park',
'playing fields',
'playpark',
'Primary and Secondary School',
'primary school',
'Primary School',
'railway line',
'residential houses',
'residential housing',
'rhe wind farm',
'Roman frontier',
'roundabout',
'Scrapdealers',
'Secondary School',
'single-track road',
'Site of Importance for Nature Conservation',
'Site of Special Scientific Interest',
'Site of Special Scientific Interest (SSSI)',
'Site of Special Scientific Interest which is the moss',
'Site of Specific Scientific Interest',
'the coast',
'the conservation village',
'the environment round here',
'the ford',
'the hill',
'the lochs',
'the moor',
'the moors',
'the old mills',
'the proposed site',
'the quarry',
'the river',
'the school',
'the site',
'the track',
'the village',
'the woods next to the site',
'this part of the country',
'the back of a housing estate',
'the back of one of the poorest housing estates in the area',
'this proposed site',
'SEPA flood risk mapping',
'the burn',
'this village',
'UNESCO site',
'Village',
'village',
'wall',
'water works',
'woodland',
'Woodlands'})

In [15]:
approved_candidate_sets = {
    category: sorted(values, key=str.casefold)
    for category, values in candidate_sets.items()}

with open("approved_masking_candidates.json", "w", encoding="utf-8") as file:
    json.dump(approved_candidate_sets, file, ensure_ascii=False, indent=2)

**MASKING**

In [72]:
INPUT_CSV = "SCOTBESS_DATASET_MASKED.csv"
APPROVED_SETS_JSON = "approved_masking_candidates.json"
OUTPUT_CSV = "SCOTBESS_DATASET_MASKED_REVIEWED_FINAL.csv"

df = pd.read_csv(INPUT_CSV)

In [ ]:
DIRECT_CATEGORIES = ["EMAIL", "PHONE", "LINK"]

DIRECT_PLACEHOLDERS = {
    "EMAIL": "[EMAIL]",
    "PHONE": "[PHONE]",
    "LINK": "[LINK]"}


def parse_entities(raw_output):
    if pd.isna(raw_output) or not str(raw_output).strip():
        return {}

    try:
        entities = (
            json.loads(raw_output)
            if isinstance(raw_output, str)
            else raw_output
        )
    except (json.JSONDecodeError, TypeError):
        return {}

    return entities if isinstance(entities, dict) else {}


def mask_direct_entities(row):
    """Mask only EMAIL, PHONE and LINK detected in this particular row."""

    if pd.isna(row["text"]):
        return row["text"]

    text = str(row["text"])
    entities = parse_entities(row["llm_entities_json"])
    matches = []

    for category in DIRECT_CATEGORIES:
        values = entities.get(category, [])

        if not isinstance(values, list):
            continue

        for raw_value in values:
            value = str(raw_value).strip()

            if not value:
                continue

            #Exact literal matching because the LLM was required to return values character-for-character from this row
            start = 0

            while True:
                position = text.find(value, start)

                if position == -1:
                    break

                matches.append({
                    "start": position,
                    "end": position + len(value),
                    "category": category,
                })

                start = position + len(value)

    #prefering longer spans if candidates overlap
    matches.sort(
        key=lambda item: (
            -(item["end"] - item["start"]),
            item["start"]))

    selected = []

    for candidate in matches:
        overlaps = any(
            candidate["start"] < existing["end"]
            and candidate["end"] > existing["start"]
            for existing in selected)

        if not overlaps:
            selected.append(candidate)

    result = text

    for match in sorted(
        selected,
        key=lambda item: item["start"],
        reverse=True):
        result = (
            result[:match["start"]]
            + DIRECT_PLACEHOLDERS[match["category"]]
            + result[match["end"]:])

    return result

In [ ]:
df["direct_masked_text"] = df.apply(mask_direct_entities, axis=1)

In [ ]:
#utuilizing regex for additional masking of emails, phone numbers and links detection, as the llm failed to detect some
def mask_contacts(text, print_masked=True):
    masked_items = []

    def repl_email(match):
        masked_items.append(("EMAIL", match.group(0)))
        return "[EMAIL]"

    def repl_phone(match):
        masked_items.append(("PHONE", match.group(0)))
        return "[PHONE]"

    #Emails
    email_pattern = r"""
    \b
    [A-Z0-9._%+-]+
    @
    [A-Z0-9.-]+
    \.
    [A-Z]{2,}
    \b
    """

    text = re.sub(email_pattern, repl_email, text, flags=re.IGNORECASE | re.VERBOSE)

    #UK-ish phone numbers
    phone_pattern = r"""
    (?<!\w)
    (?:
        (?:\+44\s?(?:\(0\)\s?)?|0)
        7\d{3}[\s\-]?\d{3}[\s\-]?\d{3}
        |
        \(0\d{2,5}\)[\s\-]?\d{3,4}[\s\-]?\d{3,4}
        |
        (?:\+44\s?(?:\(0\)\s?)?|0)
        \d{2,5}[\s\-]?\d{3,4}[\s\-]?\d{3,4}
    )
    (?!\w)
    """

    text = re.sub(phone_pattern, repl_phone, text, flags=re.VERBOSE)

    if print_masked and masked_items:
        print(f"\nMASKED CONTACTS:")
        for kind, item in masked_items:
            print(f"{kind}: {item}")
        print("-" * 80)

    return text

In [ ]:
def mask_links(text, print_masked=True):
    masked_items = []

    def repl(match):
        masked_items.append(match.group(0))
        return "[LINK]"

    link_pattern = r"""
    (?:
        https?://[^\s<>()]+
        |
        www\.[^\s<>()]+
    )
    """

    text = re.sub(link_pattern, repl, text, flags=re.IGNORECASE | re.VERBOSE)

    if print_masked and masked_items:
        print(f"\nMASKED LINKS:")
        for item in masked_items:
            print(item)
        print("-" * 80)

    return text

In [77]:
def mask_references(text, print_masked=True):
    masked_items = []

    def repl(match):
        masked_items.append(match.group(0))
        return "[APPLICATION_CODE]"

    reference_pattern = r"""
    (?<![A-Z0-9])
    (?:
        ECU\d{5,}
        |EC\d{5,}
        |APP/\d{4}/\d{3,6}
        |ENQ/\d{4}/\d{3,6}
        |LIVE/\d{3,6}/[A-Z]+/\d{2,4}
        |P/\d{2}/\d{3,6}(?:/[A-Z]+)?
        |\d{2}/\d{3,6}/[A-Z0-9]+
        |\d{3,6}/[A-Z]+/\d{2,4}
    )
    (?![A-Z0-9])
    """

    text = re.sub(reference_pattern, repl, text, flags=re.IGNORECASE | re.VERBOSE)

    if print_masked and masked_items:
        print(f"\nMASKED REFERENCES:")
        for item in masked_items:
            print(item)
        print("-" * 80)

    return text

In [78]:
def pii_masking_pipeline(text, print_masked=True):
    text = mask_contacts(text, print_masked=print_masked)
    text = mask_links(text, print_masked=print_masked)

    return text

In [ ]:
df["regex_masked_text"] = df["direct_masked_text"].apply(lambda text: pii_masking_pipeline(text, print_masked=True))

MASKED LINKS:
https://www.nasa.gov/sites/default/files/atoms/files/nabw20_fire_gas_char_studies_liion_cells_batt_djuarez-
--------------------------------------------------------------------------------

MASKED LINKS:
www.ssen.co.uk
--------------------------------------------------------------------------------

MASKED LINKS:
https://hansard.parliament.uk/Commons/2022-09-07/debates/FB0D6FE6-CF3E-
--------------------------------------------------------------------------------

MASKED LINKS:
https://online.aberdeenshire.gov.uk/smrpub/master/detail.aspx?Authority=ASH&refno=NO87NW0
--------------------------------------------------------------------------------

MASKED LINKS:
https://www.gov.uk/government/publications/grid-scale-electrical-energystorage-systems-health-
https://www.gov.uk/government/publications/grid-scale-electrical-energystorage-systems-health-
--------------------------------------------------------------------------------

MASKED CONTACTS:
PHONE: 000000211
--------------------------------------------------------------------------------

MASKED LINKS:
https://www.nature.scot/doc/recommended-bird-survey-methods-inform-impact-assessment-onshore-windfarms
https://www.nature.scot/doc/assessing-connectivity-special-protection-areas
https://greenlandwhitefront.org/gb-site-inventory/north-highland/40-loch-of-mey/
https://www.nature.scot/doc/guidance-assessing-cumulative-impacts-onshore-wind-farms-birds
https://www.nature.scot/doc/guidance-assessing-cumulative-impacts-onshore-wind-farms-birds
https://community.rspb.org.uk/ourwork/b/science/posts/the-curlew-trial-management-project
https://doi.org/10.1016/j.jnc.2023.126353
https://www.bto.org/volunteer-surveys/bbs/latest-results/population-trends
https://www.nature.scot/doc/disturbance-distances-selected-scottish-bird-species-naturescot-guidance
https://www.nature.scot/doc/guidance-assessing-significance-impacts-bird-populations-onshore-wind-farms-do-not-
https://wam.highland.gov.uk/wam/files/DBD227E31E828CDF67AD72145956210A/pdf/13_02682_FUL-Issued-
--------------------------------------------------------------------------------

MASKED LINKS:
https://www.luke.fi/en/news/review-several-groups-of-birds-
--------------------------------------------------------------------------------

MASKED LINKS:
https://assets.publishing.service.gov.uk/media/675bfaa4cĩf84c3b2bcf986/clean-power-2030-action-plan.pdf
--------------------------------------------------------------------------------

MASKED LINKS:
https://gowlingwlg.com/insights-resources/articles/2025/grid-
https://www.ofgem.gov.uk/press-release/clean-power-2030-one-step-closer-proposed-new-fast-track-grid-
https://www.herbertsmithfreehills.com/notes/energy/2025-posts/Clean-Power-2030--REMA-Update-–-major-
--------------------------------------------------------------------------------

MASKED LINKS:
https://www.bbc.co.uk/news/articles/c5yg47eryleo
--------------------------------------------------------------------------------

MASKED LINKS:
https://doi.org/10.1007/s10694-024-
--------------------------------------------------------------------------------

In [ ]:
#masking of the reviewed categories
REVIEWED_CATEGORIES = [
    "APPLICATION_CODE",
    "PERSON",
    "ORGANIZATION",
    "PLACE"]

with open(APPROVED_SETS_JSON, "r", encoding="utf-8") as file:
    loaded_sets = json.load(file)

approved_sets = {
category: {
        str(value).strip()
        for value in loaded_sets.get(category, [])
        if str(value).strip()}
    for category in REVIEWED_CATEGORIES}

for category, values in approved_sets.items():
    print(f"{category}: {len(values)} reviewed values")

APPLICATION_CODE: 144 reviewed values
PERSON: 142 reviewed values
ORGANIZATION: 264 reviewed values
PLACE: 1399 reviewed values

In [ ]:
REVIEWED_PLACEHOLDERS = {
    "APPLICATION_CODE": "[APPLICATION_CODE]",
    "PERSON": "[PERSON]",
    "ORGANIZATION": "[ORGANIZATION]",
    "PLACE": "[PLACE]"}


def compile_value_pattern(values):
    values = {
        str(value).strip()
        for value in values
        if str(value).strip()}

    if not values:
        return None

    ordered_values = sorted(values, key=lambda value: (-len(value), value.casefold()))

    return re.compile(
        r"(?<!\w)(?:"
        + "|".join(re.escape(value) for value in ordered_values)
        + r")(?![\w'’])")


reviewed_patterns = {category: compile_value_pattern(approved_sets[category]) for category in REVIEWED_CATEGORIES}


def mask_reviewed_entities(text):
    if pd.isna(text):
        return text

    text = str(text)
    matches = []

    for category, pattern in reviewed_patterns.items():
        if pattern is None:
            continue

        for match in pattern.finditer(text):
            matches.append({
                "start": match.start(),
                "end": match.end(),
                "category": category})

    #prefers the longest value, such as an organization name, over a shorter place contained inside it
    matches.sort(
        key=lambda item: (
            -(item["end"] - item["start"]),
            item["start"]))

    selected = []

    for candidate in matches:
        overlaps = any(
            candidate["start"] < existing["end"]
            and candidate["end"] > existing["start"]
            for existing in selected)

        if not overlaps:
            selected.append(candidate)

    result = text

    for match in sorted(
        selected,
        key=lambda item: item["start"],
        reverse=True,):
        result = (
            result[:match["start"]]
            + REVIEWED_PLACEHOLDERS[match["category"]]
            + result[match["end"]:])

    return result

In [82]:
df["reviewed_masked_text"] = (df["regex_masked_text"].apply(mask_reviewed_entities))

In [83]:
#fallback regex masking for application reference codes.
def mask_references(text, print_masked=True):
    masked_items = []

    def repl(match):
        masked_items.append(match.group(0))
        return "[APPLICATION_CODE]"

    reference_pattern = r"""
    (?<![A-Z0-9])
    (?:
        ECU\d{5,}
        |EC\d{5,}
        |APP/\d{4}/\d{3,6}
        |ENQ/\d{4}/\d{3,6}
        |LIVE/\d{3,6}/[A-Z]+/\d{2,4}
        |P/\d{2}/\d{3,6}(?:/[A-Z]+)?
        |\d{2}/\d{3,6}/[A-Z0-9]+
        |\d{3,6}/[A-Z]+/\d{2,4}
    )
    (?![A-Z0-9])
    """

    text = re.sub(reference_pattern, repl, text, flags=re.IGNORECASE | re.VERBOSE)

    if print_masked and masked_items:
        print(f"\nMASKED REFERENCES:")
        for item in masked_items:
            print(item)
        print("-" * 80)

    return text

In [84]:
def pii_masking_pipeline(text, print_masked=True):
    text = mask_references(text, print_masked=print_masked)

    return text

In [85]:
df["final_masked_text"] = df["reviewed_masked_text"].apply(
    lambda text: pii_masking_pipeline(text, print_masked=True))

MASKED REFERENCES:
21/05467/FULby
--------------------------------------------------------------------------------

MASKED REFERENCES:
ECU00005190
13/02682/FUL25
--------------------------------------------------------------------------------

MASKED REFERENCES:
ECU00003458
--------------------------------------------------------------------------------

In [ ]:
#for inspection
display(
    df[
        [
            "text",
            "masked_text",          #old LLM-generated text, audit only
            "direct_masked_text",   #row-specific LLM EMAIL/PHONE/LINK
            "regex_masked_text",    #regex contacts/links/references
            "reviewed_masked_text",    #reviewed entity-set result
            "final_masked_text", # with fallback for application reference codes applied
            "llm_entities_json"
        ]].head(2))


OUTPUT_COLUMNS = [
    "project",
    "filename",
    "source",
    "final_masked_text"]

df[OUTPUT_COLUMNS].to_csv(OUTPUT_CSV, index=False, encoding="utf-8",)
df.to_excel("SCOTBESS_DATASET_MASKED_AND_REVIEWED_FINAL.xlsx", index=False)

,text,masked_text,direct_masked_text,regex_masked_text,reviewed_masked_text,final_masked_text,llm_entities_json
0,The ground on which the proposed energy site i...,The ground on which the proposed energy site i...,The ground on which the proposed energy site i...,The ground on which the proposed energy site i...,The ground on which the proposed energy site i...,The ground on which the proposed energy site i...,"{""EMAIL"": [], ""PHONE"": [], ""LINK"": [], ""APPLIC..."
1,We have serious reservations that there has no...,We have serious reservations that there has no...,We have serious reservations that there has no...,We have serious reservations that there has no...,We have serious reservations that there has no...,We have serious reservations that there has no...,"{""EMAIL"": [], ""PHONE"": [], ""LINK"": [""https://w..."

In [87]:
df.to_excel("SCOTBESS_DATASET_MASKED_AND_REVIEWED_FINAL.xlsx", index=False)