In [ ]:
import bs4 as bs
import requests
import pandas as pd

Data preparation: extracting URLs for the project subpages that lead directly to the Public Representations tab, which contains the relevant documents.

In [ ]:
projects_list = pd.read_csv("scotland.txt", sep ="\t", engine="python")
projects_list.index = projects_list.index + 1
projects_list.head(10)
#list made as of 27.01.2026

,ECU Reference,Project Name,Case Type,Project Type,Case Status Type
1,ECU00003354,Tealing Battery Energy Storage farm,Development,Battery Energy Storage System,Consented
2,ECU00003435,Kilmarnock South Battery Electricity Storage S...,Development,Battery Energy Storage System,Consented
3,ECU00003458,Coalburn Energy Storage Project(ECU36COALBURN),Development,Battery Energy Storage System,Consented
4,ECU00003469,Devilla Energy Storage Project,Development,Battery Energy Storage System,Consented
5,ECU00004491,"Keithick, Stirling 50.1MW BESS",Development,Battery Energy Storage System,Withdrawn
6,ECU00004539,PLANNING APPLICATION FOR HOLMQUARRY ROAD BATTE...,Development,Battery Energy Storage System,Consented
7,ECU00004543,Linwood Battery Energy Storage System (BESS),Development,Battery Energy Storage System,Consented
8,ECU00004544,Stanely Water Battery Energy Storage System,Development,Battery Energy Storage System,Consented
9,ECU00004590,Battery Storage System (BESS) | Saturland Farm...,Development,Battery Energy Storage System,Consented
10,ECU00004596,"Holmquarry Road, Kilmarnock, KA1 4DA",Development,Battery Energy Storage System,Pre Application Complete

In [ ]:
project_ref = projects_list["ECU Reference"]
project_ref

1     ECU00003354
2     ECU00003435
3     ECU00003458
4     ECU00003469
5     ECU00004491
         ...
90    ECU00006111
91    ECU00006121
92    ECU00006154
93    ECU00006204
94    ECU00006245
Name: ECU Reference, Length: 94, dtype: object

In [ ]:
url_base = "https://www.energyconsents.scot/ApplicationDetails.aspx?cr="
url_pubrep = "&T=4"


urls =[]
for item in project_ref:
    target_url = f"{url_base}{item}{url_pubrep}"
    urls.append(target_url)

projects_list["Url"] = urls

In [ ]:
pd.set_option("display.max_colwidth", None)
projects_list

,ECU Reference,Project Name,Case Type,Project Type,Case Status Type,Url
1,ECU00003354,Tealing Battery Energy Storage farm,Development,Battery Energy Storage System,Consented,https://www.energyconsents.scot/ApplicationDetails.aspx?cr=ECU00003354&T=4
2,ECU00003435,Kilmarnock South Battery Electricity Storage System (BESS),Development,Battery Energy Storage System,Consented,https://www.energyconsents.scot/ApplicationDetails.aspx?cr=ECU00003435&T=4
3,ECU00003458,Coalburn Energy Storage Project(ECU36COALBURN),Development,Battery Energy Storage System,Consented,https://www.energyconsents.scot/ApplicationDetails.aspx?cr=ECU00003458&T=4
4,ECU00003469,Devilla Energy Storage Project,Development,Battery Energy Storage System,Consented,https://www.energyconsents.scot/ApplicationDetails.aspx?cr=ECU00003469&T=4
5,ECU00004491,"Keithick, Stirling 50.1MW BESS",Development,Battery Energy Storage System,Withdrawn,https://www.energyconsents.scot/ApplicationDetails.aspx?cr=ECU00004491&T=4
...,...,...,...,...,...,...
90,ECU00006111,Achies BESS,Development,Battery Energy Storage System,Consultation,https://www.energyconsents.scot/ApplicationDetails.aspx?cr=ECU00006111&T=4
91,ECU00006121,Rothienorman 500MW Blackford Renewables Ltd.,Development,Battery Energy Storage System,Consultation,https://www.energyconsents.scot/ApplicationDetails.aspx?cr=ECU00006121&T=4
92,ECU00006154,Limekiln BESS,Development,Battery Energy Storage System,Consultation,https://www.energyconsents.scot/ApplicationDetails.aspx?cr=ECU00006154&T=4
93,ECU00006204,Peterhead Flexpower 500MW BESS,Development,Battery Energy Storage System,Consultation,https://www.energyconsents.scot/ApplicationDetails.aspx?cr=ECU00006204&T=4
94,ECU00006245,East Rogerton BESS,Development,Battery Energy Storage System,Consideration,https://www.energyconsents.scot/ApplicationDetails.aspx?cr=ECU00006245&T=4

In [ ]:
projects_list.to_csv("energyconsents_df_with_links.csv", index=False)